[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "aea6d2adb32b46846fca35f819f41ea459d76501"
julia_version = "1.10.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "37c1de88162a743d6460ca4e0c42468287f33680c8be55c9b62b77b4de3a4552"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+2/GAP_pkg_juliainterface.v0.800.201.aarch64-apple-darwin-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "7ad4b75868db9e5ad08c70f61166ebe4a40b4dc8"
julia_version = "1.7.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "e8b761b8f62e30751a0771b1cbe1cf4eb15bc50f8a386f8637e2bd6acd86c2d0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+2/GAP_pkg_juliainterface.v0.800.201.aarch64-apple-darwin-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "1d3a5ee43cf314c759bb4a707df336cc39862d7b"
julia_version = "1.8.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "8eaf1607eee6041de6215afd6391fca909a79b1159026262d1aa3bc4d5f0dd3b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+2/GAP_pkg_juliainterface.v0.800.201.aarch64-apple-darwin-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "63e02e64f5c58f130baadf814453eee37b79dd08"
julia_version = "1.9.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "e17dce0622da3c722ecf8346359375794de28afe61ed6a124196dac002afa4ef"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+2/GAP_pkg_juliainterface.v0.800.201.aarch64-apple-darwin-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "edac495bbf2dc088644cb5685067fd5b7a06b5aa"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "1e732349b2e472441cb06fec5bd477698f4bceb8cc94e71000ef4e51b4ae9495"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+2/GAP_pkg_juliainterface.v0.800.201.aarch64-linux-gnu-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "1081100ca318daab500704dc60c77e3eb126e640"
julia_version = "1.6.3"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "f510b8747761e4ef529b59661ddd37983aa002f08d6476dfad78d39e4635cff4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+2/GAP_pkg_juliainterface.v0.800.201.aarch64-linux-gnu-julia_version+1.6.3.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "ed4dba930043b38e6e13632c666b9ff51f7dd53f"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "1ea7b99057b7b0b54e2dc35b5482982b0123e22a345c24867b7c5fb3bea48d09"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+2/GAP_pkg_juliainterface.v0.800.201.aarch64-linux-gnu-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "a68da90154e671874f7f71e1032e6323d7c2ac79"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "c615e1ff359fa90221594e039a278ba2925410924e01a92d111a9a9ff4eef79e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+2/GAP_pkg_juliainterface.v0.800.201.aarch64-linux-gnu-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "edac495bbf2dc088644cb5685067fd5b7a06b5aa"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "1e732349b2e472441cb06fec5bd477698f4bceb8cc94e71000ef4e51b4ae9495"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+2/GAP_pkg_juliainterface.v0.800.201.aarch64-linux-gnu-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "ead49c50cbf702fa384f0ce60c989be82c1ea7de"
julia_version = "1.10.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "6c5f2ad51823be22073a35891f2b8a7708f9bc985505fe9b5caa3f47d3758f8f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+2/GAP_pkg_juliainterface.v0.800.201.aarch64-linux-musl-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "8a884dbbe115f24b767db93f06bb38515cb89f4f"
julia_version = "1.6.3"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "cffaa7bbb837f21878ab19377620fe351783e2c9366b157f19f90042523d003f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+2/GAP_pkg_juliainterface.v0.800.201.aarch64-linux-musl-julia_version+1.6.3.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "08eecc559af7cfd6b77357795d900522da0a193b"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "3629365dee0282184d87dd07a889ccc2c489546d1fa3f8a35c6a4eb296a4a0b2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+2/GAP_pkg_juliainterface.v0.800.201.aarch64-linux-musl-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "3f49e482ae4b34a88401ec6d39244a5afceb0ddd"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "682fc647e5b2e23b8ad25d0e59db148991e8e962027a282b74845d2d30c52ab3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+2/GAP_pkg_juliainterface.v0.800.201.aarch64-linux-musl-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "ead49c50cbf702fa384f0ce60c989be82c1ea7de"
julia_version = "1.9.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "6c5f2ad51823be22073a35891f2b8a7708f9bc985505fe9b5caa3f47d3758f8f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+2/GAP_pkg_juliainterface.v0.800.201.aarch64-linux-musl-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "2adfc421da22a48cd64536cbcf61954cdcab0331"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "f42636d8ee9e33e8355049ee0b388c863a37d9d95d7e3a1b24ac7ea64031a314"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+2/GAP_pkg_juliainterface.v0.800.201.powerpc64le-linux-gnu-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "352849bcb030b50b24e803989178d434bb5750c7"
julia_version = "1.6.3"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "15934892017dac30b5fd8a5b86004ec5fc219bd86b7edf2049e7b4e7df074b37"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+2/GAP_pkg_juliainterface.v0.800.201.powerpc64le-linux-gnu-julia_version+1.6.3.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "448500d4b65db1cd6a5a944e8bcb73029a02eb0d"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "9ccf61277d540a4702e7ef7619101557fd0233a9711b506175e807f9629e9bf5"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+2/GAP_pkg_juliainterface.v0.800.201.powerpc64le-linux-gnu-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "62b32976348c1f3e3b1b43054fc11e50e7d8860f"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "bbee723116468b6d3963a050388c500a5f77e9dfed85efbe072e14a2382e89ca"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+2/GAP_pkg_juliainterface.v0.800.201.powerpc64le-linux-gnu-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "2adfc421da22a48cd64536cbcf61954cdcab0331"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "f42636d8ee9e33e8355049ee0b388c863a37d9d95d7e3a1b24ac7ea64031a314"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+2/GAP_pkg_juliainterface.v0.800.201.powerpc64le-linux-gnu-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "8b95c33d87999675d4e0b606b94bebc9aa6fce00"
julia_version = "1.10.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "c395ee556e91dae0c866d6741cc614db23cd22ea687290977dbf7188905128a1"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+2/GAP_pkg_juliainterface.v0.800.201.x86_64-apple-darwin-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "4382a6423fcf7dff1f7bbcb46a520df7e0d9e237"
julia_version = "1.6.3"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "56596f6e22a3aed0fe802305b09d064b15deab7206468c3a6705d6be27d1e050"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+2/GAP_pkg_juliainterface.v0.800.201.x86_64-apple-darwin-julia_version+1.6.3.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "d63fa2243ca714b7fa41588d1e412e60d4136ad2"
julia_version = "1.7.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "03c7b474a06f5d7593d6753e0642a85ebef443aeee7d6d402a91bda991e90ba8"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+2/GAP_pkg_juliainterface.v0.800.201.x86_64-apple-darwin-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "e3d91ab271bb3667f49ddee1b2000d124125953e"
julia_version = "1.8.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "ffda87b5543b350370ca8526d577d3b5d637eb3075f20a1447d4f0ae163f5ef3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+2/GAP_pkg_juliainterface.v0.800.201.x86_64-apple-darwin-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "a6e59c5eb45ce9d9513b0db4a35e9b5056a3595a"
julia_version = "1.9.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "4416650af1285807679b5cbebbe560f76297351e4823effa5f29a82e6664b4ec"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+2/GAP_pkg_juliainterface.v0.800.201.x86_64-apple-darwin-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "77a0d810079376ebdcc1643a0e324107f304e7a2"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "7ac6d4ec4de6af47ef721c5d91fb19152aceb0606b9ea7436847cb4a2b6e4be0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+2/GAP_pkg_juliainterface.v0.800.201.x86_64-linux-gnu-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "254618f460fae5c61181f302da32aaf725ba80b0"
julia_version = "1.6.3"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "4da13092aeb04b8b4f7653b395bc524ea6f191919cfb7da2db6be846e559d082"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+2/GAP_pkg_juliainterface.v0.800.201.x86_64-linux-gnu-julia_version+1.6.3.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "c57ef2dcbda3e5dbdea747b4e403c7e7ecb9a382"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "d358b448883b146214ef0ff3fc47500023e73f7d85b8ed0656382ab2ec2b7414"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+2/GAP_pkg_juliainterface.v0.800.201.x86_64-linux-gnu-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "3178f2673dfbca96a1b950d66be9d4b60f1268f6"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "4c9bffce9e4f661395cc3e3fa28e4ae5e4de692ed4fb323edfcdc57ddc2deb69"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+2/GAP_pkg_juliainterface.v0.800.201.x86_64-linux-gnu-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "77a0d810079376ebdcc1643a0e324107f304e7a2"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "7ac6d4ec4de6af47ef721c5d91fb19152aceb0606b9ea7436847cb4a2b6e4be0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+2/GAP_pkg_juliainterface.v0.800.201.x86_64-linux-gnu-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "1e8b4fbbe1342d780938dda09fece1309f81ae8b"
julia_version = "1.10.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "9e016d942afda3e69acddff490e9f55336c28cf41348a1a29fd73323eb30c8aa"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+2/GAP_pkg_juliainterface.v0.800.201.x86_64-linux-musl-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "0d7c2003af01e8f5a44a56f6c382ce2ade441323"
julia_version = "1.6.3"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "01692657535f718f5a1ebd3e7c290b4a35a6ab581752b9e03b71f45ae8b72d05"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+2/GAP_pkg_juliainterface.v0.800.201.x86_64-linux-musl-julia_version+1.6.3.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "8a7721704b78ba4e04b97bbe41410048ddcbe9b9"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "04800e126ee98fd2f611a29ed9524409de9730e09454dab096e179d4e2c78d64"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+2/GAP_pkg_juliainterface.v0.800.201.x86_64-linux-musl-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "923a90c3f09a0e64413e50b186280dfd449e8956"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "b31b091ed7215b72bc602bd70fd10cdadbfa8ead53858f0d0157d9332cfed2a4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+2/GAP_pkg_juliainterface.v0.800.201.x86_64-linux-musl-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "1e8b4fbbe1342d780938dda09fece1309f81ae8b"
julia_version = "1.9.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "9e016d942afda3e69acddff490e9f55336c28cf41348a1a29fd73323eb30c8aa"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+2/GAP_pkg_juliainterface.v0.800.201.x86_64-linux-musl-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "e05a26c0e5f45918cc0cac670284a71b6fecb894"
julia_version = "1.10.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "7ddf17893dc86a79f4e176ce8209f36650f0fd5b95098cb0d55c27c3af3878a8"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+2/GAP_pkg_juliainterface.v0.800.201.x86_64-unknown-freebsd-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "e73690463574d75599a793363a6e9f3e4e3c4557"
julia_version = "1.6.3"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "a8596369b6a308810a0514a06a6c217a23c39fd52861507df7a70b851f387d59"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+2/GAP_pkg_juliainterface.v0.800.201.x86_64-unknown-freebsd-julia_version+1.6.3.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "addda3a9cb6b21fdb27c3fbb1cb8818643df849a"
julia_version = "1.7.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "cec65b3089e645f81a5f41849fedc1b99b02460277cbe4a5c2deb51063f97487"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+2/GAP_pkg_juliainterface.v0.800.201.x86_64-unknown-freebsd-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "fc5bbe085de54424fa092affe632ef0c19f7d8a5"
julia_version = "1.8.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "1911ed6f23c8ff6eb18d401bbcec4fc6eac0ceef7ae9e6462943fa7ceec52149"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+2/GAP_pkg_juliainterface.v0.800.201.x86_64-unknown-freebsd-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "e05a26c0e5f45918cc0cac670284a71b6fecb894"
julia_version = "1.9.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "7ddf17893dc86a79f4e176ce8209f36650f0fd5b95098cb0d55c27c3af3878a8"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+2/GAP_pkg_juliainterface.v0.800.201.x86_64-unknown-freebsd-julia_version+1.9.0.tar.gz"
