[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "acc3f99414db7e8da703cd1044cf67f6fe4b7a2c"
julia_version = "1.7.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "5d6e5024c680f7b995b1b19aa6113e248bd8464e8ad596d65cd069eeb9bf8f30"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+1/GAP_pkg_juliainterface.v0.800.200.aarch64-apple-darwin-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "1bdd9615faaeea3b7a8347e5c9ff0a15686d403f"
julia_version = "1.8.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "3b0d5c709a0e6c5a8f3bd544a6edf6faa94202d731f31aa3fac7d4967bfa5f40"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+1/GAP_pkg_juliainterface.v0.800.200.aarch64-apple-darwin-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "716a7fad8bb2890cd82b2f5f25b06dc8ac81f2e5"
julia_version = "1.9.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "a7c6268c580de741d7967845d26c2084c1e61f47821f61e079e348f3c448c6c5"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+1/GAP_pkg_juliainterface.v0.800.200.aarch64-apple-darwin-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "a5223690d94b3af2618caf668f311b7c9001c6a4"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "c1dd474768d641622ac86f0002aa748a85cf5dd6ccc55da20ff97574e12b8b95"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+1/GAP_pkg_juliainterface.v0.800.200.aarch64-linux-gnu-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "697c95e482205f4696d3a7b920b830975823a164"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "0bdedbb3df456613f676527a604e43f09a336f8db2fcf27998263455c5955117"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+1/GAP_pkg_juliainterface.v0.800.200.aarch64-linux-gnu-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "d88e63542959ac56ec0791d4b73b531892f6e54b"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "a57889dc060a5a35d8b02c0ed0848dc96ff74a9ab303af1a76082be9a2424ee0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+1/GAP_pkg_juliainterface.v0.800.200.aarch64-linux-gnu-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "4e6a6df67444cac1ded5a2fd4e66dce3517810d4"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "d7d5d61574172a68c992055150bbde68e13d79ae185e96c0f9cdfecd63ac8fae"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+1/GAP_pkg_juliainterface.v0.800.200.aarch64-linux-gnu-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "1a78070145c57745371566cde77630236cd71b78"
julia_version = "1.6.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "a4ff2d62101f572c845b2670ee9eb339cf9047acd8145a801206a93b58eff2d4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+1/GAP_pkg_juliainterface.v0.800.200.aarch64-linux-musl-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "caff90b6dfb20ceb1c3d5a848554f1767058692c"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "eff92c57a152d66df8f64e2cb2352c92bbff4337e92feb622c91a765e629da21"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+1/GAP_pkg_juliainterface.v0.800.200.aarch64-linux-musl-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "c0215b1a9cec4e380815b5ec573e9e79647ab4f9"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "2f2ea641dfe3814688cd8977fc8e20c59552ad39d68d8b7a01127612c54eeceb"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+1/GAP_pkg_juliainterface.v0.800.200.aarch64-linux-musl-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "cc069d620522eeeb120d39f631413ed458d057eb"
julia_version = "1.9.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "f53d058bcf189b224b7ca9574232281cf38ee1ccaa4820bc4f87d8e932925d8a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+1/GAP_pkg_juliainterface.v0.800.200.aarch64-linux-musl-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "4adf30666c476585fa7792c687d23077494ff8bc"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "7ee9a39fefb7d057ba3f4f85199442490b060fdac1f8d14a87196644e6fdde05"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+1/GAP_pkg_juliainterface.v0.800.200.powerpc64le-linux-gnu-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "8915cd8e07db937e0c99c8be5d30b65c874b2741"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "b7a8305f0621fc966a15cfe3a833a74e14184badb62c1f2c0512aa614ab19045"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+1/GAP_pkg_juliainterface.v0.800.200.powerpc64le-linux-gnu-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "1437881f2eb21d4a333e8607ba5e3d6554b66d14"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "99077c6d5827037e5535752bc575027471dc8ee08d2595a2b5a4ecf3ab10fdee"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+1/GAP_pkg_juliainterface.v0.800.200.powerpc64le-linux-gnu-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "55fc962402c2dc1e57eaaf493e4da9316ed648dd"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "5802b58bc1c48a284ff60966769f589453d97f6f0d6601860fa70ed6526bbb60"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+1/GAP_pkg_juliainterface.v0.800.200.powerpc64le-linux-gnu-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "b6ffb682a5c87ffab46c69854f1b7716376bc6d9"
julia_version = "1.6.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "d486c6db10b6b2de9cb6b3708503a88aab091b84958dfcd8bc4151a8520df422"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+1/GAP_pkg_juliainterface.v0.800.200.x86_64-apple-darwin-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "e250a88c24e51dcdd4cf74168a74a4b20cb19946"
julia_version = "1.7.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "7f2a5b208dfb159595979c7fff011343de25dec2d9b7494be0d998303a1b40de"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+1/GAP_pkg_juliainterface.v0.800.200.x86_64-apple-darwin-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "1efd33fd830df62e54d613687f0aa0cf63b102f7"
julia_version = "1.8.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "f97f793126674afde5737dfe318cc7723580083aad7345ce334c1f23201337a9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+1/GAP_pkg_juliainterface.v0.800.200.x86_64-apple-darwin-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "b3d7933bc2c6c5639f94b820633d7b56dea67b78"
julia_version = "1.9.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "8f09585488741fccda33a7b0c283e8d5c99de2960252fa1f6edcaa3de096e681"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+1/GAP_pkg_juliainterface.v0.800.200.x86_64-apple-darwin-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "d8ff73b43b8570b7f366b0100e4c5cf5794bc256"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "833e6dadb7dbbbf6e608571821c1d5f019457093b5c471939fd1d25bc901979e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+1/GAP_pkg_juliainterface.v0.800.200.x86_64-linux-gnu-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "8ab901f53124c741a6834687509dabd2b6994e6a"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "3f97a020970e474a8e2f69b5607f84b959dbc5acfcb4bd2b3ae63f9bbb3bd131"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+1/GAP_pkg_juliainterface.v0.800.200.x86_64-linux-gnu-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "719669f1476be8bb1f862d286cdb51f3faeafce9"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "5190ecc8a147c1cdfa5df85f86dac3b392387e9f77dda8d99954ea4c69c64545"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+1/GAP_pkg_juliainterface.v0.800.200.x86_64-linux-gnu-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "78c2f8f31449087d4540d02d54f66e63fb56888e"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "063adf2b11ea0c4923fe84cbdde11c92f1fde1075e102781e9e58a1870bbc7ed"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+1/GAP_pkg_juliainterface.v0.800.200.x86_64-linux-gnu-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "e74d9a9328c1c7ab61508cff41e2c6d0dd1d3f35"
julia_version = "1.6.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "de3f4c8b04dab9b59d63b98ef2b60d59ef31b00092dafee56aacf8b3bfb589d0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+1/GAP_pkg_juliainterface.v0.800.200.x86_64-linux-musl-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "0cfec305a4dc653c202641762152f528830bc8d5"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "70232e11f782a99cf7fefddc43651795d35a3bd3b50d44b5880cafdb67e8457f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+1/GAP_pkg_juliainterface.v0.800.200.x86_64-linux-musl-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "a95733f7f451d87f95db79cf80daef6fb034ca51"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "33f83b20a8013dfee2f4d731a817c3057862bdf6cad122f78528a47478fe54d9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+1/GAP_pkg_juliainterface.v0.800.200.x86_64-linux-musl-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "9f7222648fe1a67e2c1ab9f110efa13f47deb719"
julia_version = "1.9.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "90663d657cb9b0bf482bdafd531c083153ef2ca5082f6884ca37dcf371bfdb76"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+1/GAP_pkg_juliainterface.v0.800.200.x86_64-linux-musl-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "d5a1670a065308ec50c028d417fdc63909a214b3"
julia_version = "1.6.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "ed9079459786b50c2c18cb63bb8ff29acffe78edcc2f51f38ff7ccc3aa6bc6a4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+1/GAP_pkg_juliainterface.v0.800.200.x86_64-unknown-freebsd-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "6d24db368ad9eb7a6eef03f27d8351d71efccae7"
julia_version = "1.7.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "9a4c8f736231548d3653fdac2917fa1d2e656ac10a66866965cdc21313934403"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+1/GAP_pkg_juliainterface.v0.800.200.x86_64-unknown-freebsd-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "cbc4ae5828ed73996c2e9719bd13b121d01b63d3"
julia_version = "1.8.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "120839fc6888ec090dcc763580190de02d4d8eee3f5d36b1ff6bad56de8dcde7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+1/GAP_pkg_juliainterface.v0.800.200.x86_64-unknown-freebsd-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "16c1b692721b6bec815a85fdc08c951363b38746"
julia_version = "1.9.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "27c4bebcfba81146699e4485eb91d6f2116adc30623bc5f6e386be83380085b3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+1/GAP_pkg_juliainterface.v0.800.200.x86_64-unknown-freebsd-julia_version+1.9.0.tar.gz"
