[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "fb5c6713ed89f52067bb49789c3d447aab51e5e9"
julia_version = "1.10.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "0db96f88caf0ffa37171c22618e31530dcb2d3352b370b42a1d391c8c507c024"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.0+0/GAP_pkg_juliainterface.v0.1500.0.aarch64-apple-darwin-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "7accb5637fdb1700d915ecc0acad2d3597950e52"
julia_version = "1.11.1"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "3f2ee5cac3103d80a676501342f7eb4f2959d624fc776d7a8ab93c1ac17838f4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.0+0/GAP_pkg_juliainterface.v0.1500.0.aarch64-apple-darwin-julia_version+1.11.1.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "ec9148103360e5e913f2d3d8a7dd2b9a211dc7ee"
julia_version = "1.12.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "88c02956a21e0744cb1bc8367a8c34c9b660d7ffd8f30295c4510d1ff7c7d812"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.0+0/GAP_pkg_juliainterface.v0.1500.0.aarch64-apple-darwin-julia_version+1.12.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "3c3f9effc88a63c8c3ef172a3f612d83bee73fcc"
julia_version = "1.13.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "7c4e8b6d4f183788c4cbe9bc66eaa809370646861dbad724cda7428be9432908"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.0+0/GAP_pkg_juliainterface.v0.1500.0.aarch64-apple-darwin-julia_version+1.13.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "1e318b976b929d605703b1fd4ac45be964a09c75"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "865a5aa6ced2e424de9db61c7422caaa3a6c3e74c9b174dc25ad8d0f8c6b3504"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.0+0/GAP_pkg_juliainterface.v0.1500.0.aarch64-linux-gnu-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "959e162c89667dd8c3bed334f329f76675909240"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "fba0dbc10c9599e816efdea12213c09d7d692e9027a82126aaafd8fe68911b1c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.0+0/GAP_pkg_juliainterface.v0.1500.0.aarch64-linux-gnu-julia_version+1.11.1.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "ac879e42313db152d7039b19ca66b4d6845f2bd4"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "6b73c8faa932150ef680f7ed3b6cfad541f3d7c24170358eae6ffa9cb6ba5c35"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.0+0/GAP_pkg_juliainterface.v0.1500.0.aarch64-linux-gnu-julia_version+1.12.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "ec7956c85af6a1f96470746b29294f2bb605e477"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "93cb262312ea03465bd7d96ce1821563859f7925c661969f0eee9afe9d1eef7f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.0+0/GAP_pkg_juliainterface.v0.1500.0.aarch64-linux-gnu-julia_version+1.13.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "168d7726827245b2a91b017c89bf1d05781cb6c7"
julia_version = "1.10.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "4500217ed9a98432b735fc52f5f494a9fac76df903c225ead9fe282a10cad3a9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.0+0/GAP_pkg_juliainterface.v0.1500.0.aarch64-linux-musl-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "8b96feafe56d10f58ae8c21b0eeae4e1138aa5ee"
julia_version = "1.11.1"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "ee6f980af65767b3e31df142c29e540cc8f2bdebfa24645b786426e41ca08e33"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.0+0/GAP_pkg_juliainterface.v0.1500.0.aarch64-linux-musl-julia_version+1.11.1.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "3bc2099743d307d5770f2f70c74611d33cbd7020"
julia_version = "1.12.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "619d4ec5beba8edbb0cba678fc0ba8396308fddc3505b6d7b333cffb9646e8bb"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.0+0/GAP_pkg_juliainterface.v0.1500.0.aarch64-linux-musl-julia_version+1.12.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "3c87768c741f4a3a5acc397b8bdc4121382f6460"
julia_version = "1.13.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "b815f698f770f355bbd0f628afac73211351490e06e37a1197e2990400a97e9d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.0+0/GAP_pkg_juliainterface.v0.1500.0.aarch64-linux-musl-julia_version+1.13.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "0b6dd116eb7d646e0eb92b1fc04b53c954787596"
julia_version = "1.12.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "566b7ba306dcad7ee243db6ea27c677d5c305e936cfa7c1fa431222d54cdf04d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.0+0/GAP_pkg_juliainterface.v0.1500.0.aarch64-unknown-freebsd-julia_version+1.12.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "2f8533f76ddc431a4c0fe3d9df9e784de6da8f2f"
julia_version = "1.13.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "856024a67adece93ec5cf0bf8682c0ca3b8d732829cddb6e48287270625cce11"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.0+0/GAP_pkg_juliainterface.v0.1500.0.aarch64-unknown-freebsd-julia_version+1.13.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "e826f19dfb0e0c94f603b6d114fd7d1b3cf57c1a"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "dba4b856e7bb241ed2fa9b914dde51d3e803deaeacd31091e9d655547246d3e9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.0+0/GAP_pkg_juliainterface.v0.1500.0.powerpc64le-linux-gnu-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "4a58dc9bd1c616ab5f6561975f4e21a327254107"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "29a504774f25ca5caf3858048858cf65bbbd2b446662a43d055e803f08df392e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.0+0/GAP_pkg_juliainterface.v0.1500.0.powerpc64le-linux-gnu-julia_version+1.11.1.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "3777aacf7d3f61a5d6509765ed159a5d3e35a5a6"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "724d572e7f5b3ba914b8f5de7f2cda4ef07a48a932f9e9989c4c1645979fc7e5"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.0+0/GAP_pkg_juliainterface.v0.1500.0.powerpc64le-linux-gnu-julia_version+1.12.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "a3e0c20709a9f073df7ce6c0c9c90b6e25e5711f"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "18e541a0699e197ab69fa7b2b68a26ec77858d1a699f40da13adf22d00851faf"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.0+0/GAP_pkg_juliainterface.v0.1500.0.powerpc64le-linux-gnu-julia_version+1.13.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "riscv64"
git-tree-sha1 = "3eb4f4b3e16dda697e8d33a310f77469ce23aa77"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "1e616c173248926c1f221d049ccd6b98d29f8c701bafc7e2ffc34e2c62c66117"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.0+0/GAP_pkg_juliainterface.v0.1500.0.riscv64-linux-gnu-julia_version+1.13.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "5a75c16f0a5f47d2980075f69074aa64212dbf0e"
julia_version = "1.10.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "55656687f5040749f3a89ec8708985e4a5fe0c6edf664f4aa94d69cc0a761625"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.0+0/GAP_pkg_juliainterface.v0.1500.0.x86_64-apple-darwin-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "c75fe6fdbfe62c19671d3aeade7cc9c665490f29"
julia_version = "1.11.1"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "8fa7a7035a7d1a7fef9a3ec518b621f63653f2e206635533522df7627772e8eb"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.0+0/GAP_pkg_juliainterface.v0.1500.0.x86_64-apple-darwin-julia_version+1.11.1.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "2cf7c64edaa2ca916a444162b168b8ebcca05945"
julia_version = "1.12.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "a78827aa703438976245284bd9510a3acf525246834e9d0d3b544aab5c049a89"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.0+0/GAP_pkg_juliainterface.v0.1500.0.x86_64-apple-darwin-julia_version+1.12.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "3b5780742059f9271c39338246a761068b4c5acd"
julia_version = "1.13.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "adb0e024a2968a55e691a6e85d478a1a76cd69694ec67bfa836315fb87827930"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.0+0/GAP_pkg_juliainterface.v0.1500.0.x86_64-apple-darwin-julia_version+1.13.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "dacf851ada707e9a668a9302b7c2ebc7fc89a337"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "fba9f603ae8ce5b7afa6422209e3292e77b04f7765f75c3b949bc65493d0bea4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.0+0/GAP_pkg_juliainterface.v0.1500.0.x86_64-linux-gnu-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "674a8109e9cbd360abf21ec1b41bdc2dacfa4e67"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "ae872807f5e7eedc86b1293816c65fe17c9dd4d9c6eea0c019a7ba9d8711d53e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.0+0/GAP_pkg_juliainterface.v0.1500.0.x86_64-linux-gnu-julia_version+1.11.1.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "66c77a059f3e406d8644ed183a16f33083c4f4ac"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "4d69bd7b802cf6b841f40fca0412c76ce057a86f1e562e36848bc2e04b5c309d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.0+0/GAP_pkg_juliainterface.v0.1500.0.x86_64-linux-gnu-julia_version+1.12.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "6a001ce878ede63b4720423a74d6840950fe7143"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "598d6186fdcc09100ecf1cf77e3573c3dea8203382a79555195eb07b9fc479a7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.0+0/GAP_pkg_juliainterface.v0.1500.0.x86_64-linux-gnu-julia_version+1.13.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "288947d0f9d088e69afe7084d28daf93c2b40c28"
julia_version = "1.10.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "df11a11f76c4cba146c007ce4efc0ae82bad2efb622c588cc33db6e6275b2bf2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.0+0/GAP_pkg_juliainterface.v0.1500.0.x86_64-linux-musl-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "d16791e9f3907f8e5660b0b7316ad564f282bd34"
julia_version = "1.11.1"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "465dc35864f3356f5f80db3407e9966a210dd9a8e5a816caa745596d5fd27a3a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.0+0/GAP_pkg_juliainterface.v0.1500.0.x86_64-linux-musl-julia_version+1.11.1.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "dc87a7b3aa2b38643cf8e44fa625efead70d7c7d"
julia_version = "1.12.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "a108d81dbf5f06e61db951922b77e1ec861a854f8bbf1ff23df510af2cb91fee"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.0+0/GAP_pkg_juliainterface.v0.1500.0.x86_64-linux-musl-julia_version+1.12.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "555c46ffa1995e28a8e34248893e4ec312a9663d"
julia_version = "1.13.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "daa9e75782cbb3ad27dd011d0a2e5dd0893c42ff429182424a24c0930d1e9852"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.0+0/GAP_pkg_juliainterface.v0.1500.0.x86_64-linux-musl-julia_version+1.13.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "e47e0795929628c4ac670434980acde659876e07"
julia_version = "1.10.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "10f3edae9a8a1bfdace86348468ab5e914daddb96e00b9b9a3aa0fba91552bdb"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.0+0/GAP_pkg_juliainterface.v0.1500.0.x86_64-unknown-freebsd-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "f4ba7e21b53db119d899aa0d015ff7784bfb3c71"
julia_version = "1.11.1"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "d284d7fb23e018fffe472db8542ad2e2d27c2f2c85e721878aca5f7991a50b2a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.0+0/GAP_pkg_juliainterface.v0.1500.0.x86_64-unknown-freebsd-julia_version+1.11.1.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "630585d94ab164c8e29cc8cb04a4960412663510"
julia_version = "1.12.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "02b9fb6a3712a7cf71e02d87dcdc7bc146fcccbc1038060a0ae7301c47b3ee22"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.0+0/GAP_pkg_juliainterface.v0.1500.0.x86_64-unknown-freebsd-julia_version+1.12.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "22760204cffbc711fc5d88e39d5a1f0e24d0133c"
julia_version = "1.13.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "d5f26d81d18a2923559863e3ea876430e027a4156ea432e4e469a2b69345a7cc"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.0+0/GAP_pkg_juliainterface.v0.1500.0.x86_64-unknown-freebsd-julia_version+1.13.0.tar.gz"
