[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "452204a1a5d48c0c022f13361ee3b6c982a4ba37"
julia_version = "1.7.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "a6d08f1f18889b8f68a8f479df1a03d3ce33d6db60821bc3f33a8f44511b0247"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+1/GAP_pkg_juliainterface.v0.700.100.aarch64-apple-darwin-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "772b7475daecfddd9c2f466f90c356a1f55700c9"
julia_version = "1.8.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "ba3ddcc4cc4de1331adfcf78deffe3ca82f5018ef363a3dfff00cbb618be3728"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+1/GAP_pkg_juliainterface.v0.700.100.aarch64-apple-darwin-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "03f929e6ccfec289d239c366cc644990ebafae46"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "ba00dc13bbe9ad5d3bb90630e49e7b5c958043f570851d094dc4cc79f310678b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+1/GAP_pkg_juliainterface.v0.700.100.aarch64-linux-gnu-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "f42dd76e508202ea8dbb9c0442c02faae3b9c9fd"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "0271596e31bddc3723c98f7c305c427e2cfd7a542aa2d54b21cdfecc755e94a9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+1/GAP_pkg_juliainterface.v0.700.100.aarch64-linux-gnu-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "ac2aee4d074978d6f557eca1fe7e4ef4f53448fb"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "c9c873f5a7a84f963aab6213890180add7e068b7759128899fd1d968149e0b00"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+1/GAP_pkg_juliainterface.v0.700.100.aarch64-linux-gnu-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "a2f0d0b9ffa355433076b62e67045812725d52c1"
julia_version = "1.6.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "db4aa651fc6dcb6e06107fe501df74965f9137889e1dc61b753f537a715127e7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+1/GAP_pkg_juliainterface.v0.700.100.aarch64-linux-musl-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "047de5df7dc165e4a9bf0dc02c1114835d8f191b"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "1fca6f30d1400f1ffab6df3a64058b8279c49ef6eecceb72a8e91896d7eaa47f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+1/GAP_pkg_juliainterface.v0.700.100.aarch64-linux-musl-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "ccf13cad4a3653ab861390cf73b91d0c4429a318"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "e984d8c81765cbc3ba1c37d0dd5073b1ad050b2fab9c279757ec3e52ea9ea5e4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+1/GAP_pkg_juliainterface.v0.700.100.aarch64-linux-musl-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "fba83804fe0b0e8a323af35e4a42b1d88693c419"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "a92073f4d155538ed7918bee1afc405accb69a1a20e5cdca1e7c3941dc3fa164"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+1/GAP_pkg_juliainterface.v0.700.100.powerpc64le-linux-gnu-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "bd137bbef7318cf343a21ca732b4b1455c53eb8f"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "e5b2015629f3babcfc9afbc387bb27d41346c38296a993fb56e5e4e984591906"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+1/GAP_pkg_juliainterface.v0.700.100.powerpc64le-linux-gnu-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "55639de2c98288c37be829044cfea49b9e899b1e"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "a105fb997f5ff1729dfe37d541db14a690b01f7b00400041155a6af29e285630"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+1/GAP_pkg_juliainterface.v0.700.100.powerpc64le-linux-gnu-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "e3d678afc0e829d5c9f53a23fdf0737d9a94d105"
julia_version = "1.6.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "890beff5f6145216dd0e30261e9666fbc3dfe5f4e4b291c4bb07ef75d8d29b82"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+1/GAP_pkg_juliainterface.v0.700.100.x86_64-apple-darwin-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "e7a38ce80188a81fb2a9000faea3351fe1887ec9"
julia_version = "1.7.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "6723da132f1b3d7690c78e05f2f0ff227dd6d71ff7f59fc2bcbbb4c542977cb8"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+1/GAP_pkg_juliainterface.v0.700.100.x86_64-apple-darwin-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "8150f24f93ad0547f4ebe970a4bfcb6e2d8327e6"
julia_version = "1.8.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "75e07ab481eeb057ffe18b2d684ebfa60b76758d1af16a781a28c64112c3bc78"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+1/GAP_pkg_juliainterface.v0.700.100.x86_64-apple-darwin-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "37b62ec4025c59701f25204caf04e853eb1ad13b"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "3449a8356d0f11d2c67db9ab12db7fdcd4c4ba8dd498684dd374a1cac08ee2bd"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+1/GAP_pkg_juliainterface.v0.700.100.x86_64-linux-gnu-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "acd2119d7baf6da83e95664d285abde63c17392f"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "151f408a172dd446b2a68132c295b2b2ec6f8352d30238093a4c598c85f6b661"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+1/GAP_pkg_juliainterface.v0.700.100.x86_64-linux-gnu-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "a8873f97a30c23f77db0f50d75be163d09b8f746"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "fe33516ba050232c758640791b2c63d2de361cb0276d0500d9395993eb29d53c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+1/GAP_pkg_juliainterface.v0.700.100.x86_64-linux-gnu-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "5d78489dbdaefe7282b607b9e948b8518382e6ab"
julia_version = "1.6.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "6d83fec4060ff8ed4db7fed32b552c1ac77a7c248d2b66c64d5bcc849218e916"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+1/GAP_pkg_juliainterface.v0.700.100.x86_64-linux-musl-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "a6a4d79e5aefb55b5e46c931c934e288c754defb"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "898ff82ea721d6d50a273e5d2163732541dad8bbf2920831f2458f162898c327"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+1/GAP_pkg_juliainterface.v0.700.100.x86_64-linux-musl-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "d0029593f1c5c124edac0cc38b67023d8db6b18d"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "6898ad1e28299c5f1918f1d031dd79c0564771a66de1f426658ebbfd0f935ebd"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+1/GAP_pkg_juliainterface.v0.700.100.x86_64-linux-musl-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "d224b274185f8ec820115153505409e7407fb370"
julia_version = "1.6.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "63450741d907613ee1731ab03c7af0321df1829cd6b952a533e4bc424cd19edf"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+1/GAP_pkg_juliainterface.v0.700.100.x86_64-unknown-freebsd-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "e053c83be522b93f9af6aa8fe8a3b6eefc1c1544"
julia_version = "1.7.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "f72ca170dbdc54afd0b8d011f84dba9fc8a511f6bed500d78fd0b166ded45824"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+1/GAP_pkg_juliainterface.v0.700.100.x86_64-unknown-freebsd-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "b4c501e88dc7bb21d7590973c268c340a3724693"
julia_version = "1.8.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "d2288b5585928a37b282ea90e95aac211f40dde481a39a352cc979eadc1851b5"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+1/GAP_pkg_juliainterface.v0.700.100.x86_64-unknown-freebsd-julia_version+1.8.0.tar.gz"
