[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "91faa41166ffbe06c133643abfe916bcec79e0d6"
julia_version = "1.10.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "a9df0e9ea5d9ef0b3c8fd8394d375443ac41d20cf4706d54c5f207c44d0908ac"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.300+0/GAP_pkg_juliainterface.v0.1500.300.aarch64-apple-darwin-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "0995e77716a9ffd7a91387ab6dba34d8ef3e7041"
julia_version = "1.11.1"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "7da3289802885d2dd65f528bcf18f599d880af417434c0ecaad4a2a8327acfed"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.300+0/GAP_pkg_juliainterface.v0.1500.300.aarch64-apple-darwin-julia_version+1.11.1.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "3aa0688c2e4c550fe5e44243613ad4ec84f2858d"
julia_version = "1.12.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "ea277a997eb37612a70e4a33dcfbc333a25be71b9e6cf9eb55d92b4b87ea1553"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.300+0/GAP_pkg_juliainterface.v0.1500.300.aarch64-apple-darwin-julia_version+1.12.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "e53b93840e81e6b4c69595ea7baba3543121e012"
julia_version = "1.13.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "a17a0cca610345ee638227915612f45e7d50c7ff3e74799887d9194b02978aa9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.300+0/GAP_pkg_juliainterface.v0.1500.300.aarch64-apple-darwin-julia_version+1.13.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "c44f3a5a2f50916bd9ee1b0a9bd953d22c7660ef"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "bc2302515791ae7cc1860df38709b108f91a85e1aad83ff8d3e81278d6e485fb"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.300+0/GAP_pkg_juliainterface.v0.1500.300.aarch64-linux-gnu-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "b91c2d2d5953272d9eaf4c6c6573df67f438f7fa"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "4cadfd308c9e192f2b722d9a673bf3aceabe7b6303098441d29015e751751761"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.300+0/GAP_pkg_juliainterface.v0.1500.300.aarch64-linux-gnu-julia_version+1.11.1.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "e8214737c0dd504c34d886dcf78cc164f697785e"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "51833057f33322f4616cac74d8b7025f24542c67ef1ff1f7921e71b5b5a9ef0e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.300+0/GAP_pkg_juliainterface.v0.1500.300.aarch64-linux-gnu-julia_version+1.12.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "3e3f7f193422f61a0315307a23ee3aeff4df56fe"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "13ab998957aed3f3fcddab937133588932358874e341d2234ce341d5c9d6ea37"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.300+0/GAP_pkg_juliainterface.v0.1500.300.aarch64-linux-gnu-julia_version+1.13.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "c68c28b93675aee7033735f9b3b383b4fbc1ac92"
julia_version = "1.10.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "53695c4b71cf8c835ee536044e28016dd46acb6158a5daf140fb9996c0d1986a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.300+0/GAP_pkg_juliainterface.v0.1500.300.aarch64-linux-musl-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "672460449397edfbc88797212698a4c1530a5bc0"
julia_version = "1.11.1"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "d5e99088241f2266ad6fbca4dd5abe580b90f338955da22e9647ceac8ac86491"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.300+0/GAP_pkg_juliainterface.v0.1500.300.aarch64-linux-musl-julia_version+1.11.1.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "f62c6c1749cdd14b902e619e909eaf57679be4e2"
julia_version = "1.12.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "0fe3596ef08805e471d363d4915a3b48617ed4609980fe15d12f4c802233667e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.300+0/GAP_pkg_juliainterface.v0.1500.300.aarch64-linux-musl-julia_version+1.12.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "bab2f93f11348442826abf39de8270ff5c131dbe"
julia_version = "1.13.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "07cd09ba0469d649561ea2f3c23ae3cc18e2cba47b38cc79bc25569fb70f692d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.300+0/GAP_pkg_juliainterface.v0.1500.300.aarch64-linux-musl-julia_version+1.13.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "92a8fae7a9272294fddacf003ee3c308f1f9f009"
julia_version = "1.12.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "8bfc9773dd837c33064892e31866573e9bbef52a9c50d0f7b01dac46cafe66d2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.300+0/GAP_pkg_juliainterface.v0.1500.300.aarch64-unknown-freebsd-julia_version+1.12.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "bed27e06f55274c5543c944f3c1539a39abdaf49"
julia_version = "1.13.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "02c02517687321e02dc0388c16b25ed3d5482efb71cdc362a7d239dee3a20380"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.300+0/GAP_pkg_juliainterface.v0.1500.300.aarch64-unknown-freebsd-julia_version+1.13.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "5a9c5f4ee9a1417303161881ddf1cd5417df3c54"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "23b28126fe3ed792b49a55ca4c7b7c4a4ec07f3bdc1fe6ecd8a628c618080479"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.300+0/GAP_pkg_juliainterface.v0.1500.300.powerpc64le-linux-gnu-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "2e9ae59296f72485a4769cd0c59e5e30300f610a"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "74f99db49c40a941264abb1bfb19ec3cae6ea6a618c2945d491392b3ef5cd7eb"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.300+0/GAP_pkg_juliainterface.v0.1500.300.powerpc64le-linux-gnu-julia_version+1.11.1.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "76c983568ed3f094402f8fc7b1ccba8132a0bb48"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "58a856a79a4fd76c6acf9664b483b90d6e02fa0a4000f7f1eb035ddf48351324"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.300+0/GAP_pkg_juliainterface.v0.1500.300.powerpc64le-linux-gnu-julia_version+1.12.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "125803667251963d5e728a7c43cd4cdd0d98e15a"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "c46e425273c3e79d73fa523dc8000dbacfd12532ad8099cd9dc403c6400c4e94"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.300+0/GAP_pkg_juliainterface.v0.1500.300.powerpc64le-linux-gnu-julia_version+1.13.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "riscv64"
git-tree-sha1 = "289cfaf2b54de7bd5f26aac2f73cc8d48ab2e011"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "87e763555eb38e6e5d9cefeac50ab38ba27c1305adb69b985b817182c4588b32"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.300+0/GAP_pkg_juliainterface.v0.1500.300.riscv64-linux-gnu-julia_version+1.13.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "4a7a7be5167df8e39435ed7179bee4464885d9f9"
julia_version = "1.10.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "a5f32845042becb45947b7853ec891a521a77cf665acf0e8b8c27dba19c0b15c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.300+0/GAP_pkg_juliainterface.v0.1500.300.x86_64-apple-darwin-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "fae37d947d53974fdf6f7624feb02d23b35c1f04"
julia_version = "1.11.1"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "29bf3fdfafc34b8dbc144236e9f8c9f0a08b02877c8ff449841a885fb44c7824"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.300+0/GAP_pkg_juliainterface.v0.1500.300.x86_64-apple-darwin-julia_version+1.11.1.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "e7512a4caec1923d5ce4fde68685c672f9164314"
julia_version = "1.12.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "42f06cc9bdd63a930323d2d37bdb6a4d44e9b370256cadf32e5288440098cea8"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.300+0/GAP_pkg_juliainterface.v0.1500.300.x86_64-apple-darwin-julia_version+1.12.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "4289ffef17444f59c86f1bde20bfaca4e7eaa968"
julia_version = "1.13.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "0af217e7aa52f2b9a546777f7abb6f9ff1be73e90756ce9647ff68730814ca0f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.300+0/GAP_pkg_juliainterface.v0.1500.300.x86_64-apple-darwin-julia_version+1.13.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "3998eb89a9c15704b65f0672e18588d6f9a61ae9"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "29c237d6789643871923ca8c5f6fbf6453eca6315474dcd154d730e318f05c63"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.300+0/GAP_pkg_juliainterface.v0.1500.300.x86_64-linux-gnu-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "f578f96a00c9bb207168ceb65de7e432d0cda70a"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "b2a066148034cb387092d6a5bf92849782443678e438c93a42457667937b1241"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.300+0/GAP_pkg_juliainterface.v0.1500.300.x86_64-linux-gnu-julia_version+1.11.1.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "1aceef837cbccd6d18dc6ce41ca55984c31af208"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "5ae65d4ffd897858b13034882bb38d52f7ca5b10f4fb480d93f5525ba5fb0c96"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.300+0/GAP_pkg_juliainterface.v0.1500.300.x86_64-linux-gnu-julia_version+1.12.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "89810ad43f59aa6b0f9dcb4c95490324b26787dc"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "4d4132214a5a366c12dc8276d2df796a71d006d0ef03815189431ef7539e08c8"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.300+0/GAP_pkg_juliainterface.v0.1500.300.x86_64-linux-gnu-julia_version+1.13.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "cbbff420c312b0da36613b1d4351ecc9b64cd000"
julia_version = "1.10.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "990d58089af23efcab1f6362d08a453c7409b930c5de89a26b364722c3b2560c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.300+0/GAP_pkg_juliainterface.v0.1500.300.x86_64-linux-musl-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "1a0832569642ac0500e627bcadbbf0d41bb8d7ea"
julia_version = "1.11.1"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "89b30cc45a1ee27064785fd46142f1f50a31be245df20bf5c413ac8abe6a04ef"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.300+0/GAP_pkg_juliainterface.v0.1500.300.x86_64-linux-musl-julia_version+1.11.1.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "ed087280d36e01b42a363d49195d8a53d89046ca"
julia_version = "1.12.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "1e85828059f32949c56ce75d0e9c75cdfeaf22c3b04d841c1c1caf42a34e99dc"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.300+0/GAP_pkg_juliainterface.v0.1500.300.x86_64-linux-musl-julia_version+1.12.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "9cfd57502cbfdf253ef5893dad5cbc2b043e4657"
julia_version = "1.13.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "7075879f7665917f94660e7ea13140ce822f57576eea3a4171ce0590124c50fb"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.300+0/GAP_pkg_juliainterface.v0.1500.300.x86_64-linux-musl-julia_version+1.13.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "f776fc1b747d5c9617943297dbde8d19a052623e"
julia_version = "1.10.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "492387e716f5a7dc6f67fd5d64e40c514bffc9761683f37787f8fdeaa76569b6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.300+0/GAP_pkg_juliainterface.v0.1500.300.x86_64-unknown-freebsd-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "f4d19827a303c66019b92fb3003e734bd4c939e1"
julia_version = "1.11.1"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "9e4d55069cdcc95f1d71ec26b66e452865065205955efc8745565a74554a4509"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.300+0/GAP_pkg_juliainterface.v0.1500.300.x86_64-unknown-freebsd-julia_version+1.11.1.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "3d3efbc98d6a0bd2901e3eb5cf11ce7defe00bd2"
julia_version = "1.12.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "f0e77e83687ca3a8a5c31fe1bda0972133f3aa64c8f803e05a89c5b1bc0199c6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.300+0/GAP_pkg_juliainterface.v0.1500.300.x86_64-unknown-freebsd-julia_version+1.12.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "6182946fe0ab571239038463ae613a50bab09a7a"
julia_version = "1.13.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "28e887f10cef76303ebb5b39ecd765d1940ae14e6a802b8a38477617b0cfd18f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.1500.300+0/GAP_pkg_juliainterface.v0.1500.300.x86_64-unknown-freebsd-julia_version+1.13.0.tar.gz"
