[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "4585afefcc680fa6b3fdab52b2907e5604a5740a"
julia_version = "1.7.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "45f35f638887af6886627cb3be68155da004b499a31de976c8efe74ef35570c5"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.0+0/GAP_pkg_juliainterface.v0.800.0.aarch64-apple-darwin-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "9443843175ce379a629e1fbe1f8eb60d2f61fdf9"
julia_version = "1.8.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "bcad30ae8266155386bf825a01a75108fa55466b18569a9a9abb7facf2bdb000"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.0+0/GAP_pkg_juliainterface.v0.800.0.aarch64-apple-darwin-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "bb1d8226000f993e80b7d3b993b50e9a7a4a25bb"
julia_version = "1.9.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "2e657c357d17f1fa5b52864d8108eccfd5db07c0137965f131a693c463bb0972"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.0+0/GAP_pkg_juliainterface.v0.800.0.aarch64-apple-darwin-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "a342115f421897a515fc6f690824bf53e75f61c4"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "0ba6479158effaf699fb730a8d00f1af47f5a95159c4b1bfca830cc5e53ec46a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.0+0/GAP_pkg_juliainterface.v0.800.0.aarch64-linux-gnu-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "495f5286cfb46eea7100286cddf7e7921bb6dd94"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "5b30e1fce9905bc975c7474b46ce3f2406b8b92bbf79d41740bc8a4782a0fac2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.0+0/GAP_pkg_juliainterface.v0.800.0.aarch64-linux-gnu-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "79c2a8a034c993ba5d5d16158aa2275645e7a7bd"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "2469cbaee08f5cb5bce90facc6f4a4014d3a60062a786ad7fbf49203abba29d6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.0+0/GAP_pkg_juliainterface.v0.800.0.aarch64-linux-gnu-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "c9438954a815f82cda9460c864ad6311cc50f93c"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "665b6ffda27d77065dfaa8aea6786543792b883a3c0ad48aff4e21308aa8e048"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.0+0/GAP_pkg_juliainterface.v0.800.0.aarch64-linux-gnu-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "2684d7d0a6f6a2e1fce69f46eb86242213ec18a8"
julia_version = "1.6.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "74d7f796ff4009987f1fe9941b1107aa4d0f3f041fce6745d9a87a020adf40b5"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.0+0/GAP_pkg_juliainterface.v0.800.0.aarch64-linux-musl-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "40fad38c6823b395d2a0de7cb240e685928050dc"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "ea86a7dce7d02f78e6653acd5dd8ffc2d95a15f6fcd52aba5926011abdc46ff3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.0+0/GAP_pkg_juliainterface.v0.800.0.aarch64-linux-musl-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "6f5a66b11045dddb2e27a2ac8b8f82db1bfa27e0"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "3fcc3bb8b8a79f8e0b9eeda01925025aa416a72c545c25dbe31d06483da311f0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.0+0/GAP_pkg_juliainterface.v0.800.0.aarch64-linux-musl-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "be407f5a97a3bce289deeb23798e1446e70e1b02"
julia_version = "1.9.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "a7ba8de782afff24bf51e7accc394045cd9e89d1a33dfa17dc81917b32e6aa14"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.0+0/GAP_pkg_juliainterface.v0.800.0.aarch64-linux-musl-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "54e144935bf5b1ba953860288f7c535ef9a83880"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "84d2d399070a4093f45cdca192c873e1c709628ad28235163b32546408f888fe"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.0+0/GAP_pkg_juliainterface.v0.800.0.powerpc64le-linux-gnu-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "43bf7fc1adec453a1e0c2afb269be636bec8d100"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "87ab41b06cce6f9788e51ee4fc20764dc7445b4d001f65ca1a76cfd104bca8df"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.0+0/GAP_pkg_juliainterface.v0.800.0.powerpc64le-linux-gnu-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "fe5f19dd2e684287122ed897aa8c4ee143a9394a"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "6db951013b7c6770253dc5caf07087571bcd90ea596dd84479157111be4abfc4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.0+0/GAP_pkg_juliainterface.v0.800.0.powerpc64le-linux-gnu-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "c2404b58c8409b66c5daeedfc42b5e91f0015862"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "146b742c2e4a122bb8d3ec7db81b9aa25dc7ab5eb33fb0e349714d59e8f3ee2d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.0+0/GAP_pkg_juliainterface.v0.800.0.powerpc64le-linux-gnu-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "01f45f4c22bde7c15b0a6f4f009d0f64979f2283"
julia_version = "1.6.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "403f9e1ff5a6b8d769f152d1a262ba263fa02ab8705060cd2c52f605e377fcb6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.0+0/GAP_pkg_juliainterface.v0.800.0.x86_64-apple-darwin-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "bfeba0fe61e9c5caa01cd73474c421dd9ef1ecac"
julia_version = "1.7.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "9d55c24fac96676b13c81ab4fce48fea030344faa07236966ff0f0b13669eb0f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.0+0/GAP_pkg_juliainterface.v0.800.0.x86_64-apple-darwin-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "4e261edce1d44b41e40aeb0993f86c6d68e8f498"
julia_version = "1.8.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "84ffa0879ec01ae6eae208e53739cc0b64da90fa88f921a626d1d308eddaab9a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.0+0/GAP_pkg_juliainterface.v0.800.0.x86_64-apple-darwin-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "482fc813f418b390f3bda854210436cc29c2f003"
julia_version = "1.9.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "e3162297e0f1f4c7dafc65b12ce8cc7b805f4c08ee5b095cb19be0f3a3755e15"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.0+0/GAP_pkg_juliainterface.v0.800.0.x86_64-apple-darwin-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "fac3d40bfec28d326880bce876307c944c44e07e"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "0503dc0c1dd0a9552d1222b394350dd2086dbf9d5deec28e2096f3fa608addb9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.0+0/GAP_pkg_juliainterface.v0.800.0.x86_64-linux-gnu-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "e3d4d865ddc0b59d31bda2f353d2d81deab177ba"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "59b84ca461ad02b17f6b4bc1ea75eb9d16a819e7a7cda6ee82b92785d089fca5"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.0+0/GAP_pkg_juliainterface.v0.800.0.x86_64-linux-gnu-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "b9593ce0e4818a3bd626d1a3ee67278416b5098b"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "5ecbdbb1e8b06e290e4913744a276c4f49c0c1d413c3a4cd01044185a7ef347c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.0+0/GAP_pkg_juliainterface.v0.800.0.x86_64-linux-gnu-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "3f25b48f5983b404cc610a7561bff904f4dc5808"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "c025ce6e725d65e73ff76548af836dc513904b14c0c53b791b319626a93cad12"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.0+0/GAP_pkg_juliainterface.v0.800.0.x86_64-linux-gnu-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "9284ebdaddeef9367029c7cdbdda0f5c0a5a610b"
julia_version = "1.6.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "3383a84e818ae78204295d7c4b7fbcfcb76519f2014cd8716a901510b78c644f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.0+0/GAP_pkg_juliainterface.v0.800.0.x86_64-linux-musl-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "195dd11c612a0772f759540ff20bce7c0e55f6a8"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "c8e7f118b984075c3b04eac870a9536fc1b8514add6d92c2d588c1f0a5ce5cb6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.0+0/GAP_pkg_juliainterface.v0.800.0.x86_64-linux-musl-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "7e5d558dfdd4cb491adbbc6596241c2f2bccf2fb"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "ad2d3326b04d0ab96b0a94e9c4869ac0e6b0859e11af4ceec161152a05a4cf63"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.0+0/GAP_pkg_juliainterface.v0.800.0.x86_64-linux-musl-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "769bdbe716db41b32bb4c2ca7fa70073d5a71888"
julia_version = "1.9.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "578c9b3ea57d3effb6eec68afe4b1b5a31ba5d8a55e216275962e9328d68fa12"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.0+0/GAP_pkg_juliainterface.v0.800.0.x86_64-linux-musl-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "6d1268ec2e311fe6eba3f6c14c3693e985c7b321"
julia_version = "1.6.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "5ef0aef45bd48e7a387dbc1f24fc893052769451d507df67e221f1d3d5cb01e7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.0+0/GAP_pkg_juliainterface.v0.800.0.x86_64-unknown-freebsd-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "6472d8c632ca62c580059148e4a5dd16882ce4f6"
julia_version = "1.7.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "dd9321873b68972462afe7aaff14ae95493e6a5d836b2646fedfd8e9dedb7567"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.0+0/GAP_pkg_juliainterface.v0.800.0.x86_64-unknown-freebsd-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "b86c8191ef5d45a591d24184601664e04c4fcda2"
julia_version = "1.8.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "d8a2b396de4f4d00ea19635c2954bc37aeb78d7b50098c28e60e4ef2dbeb3bd2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.0+0/GAP_pkg_juliainterface.v0.800.0.x86_64-unknown-freebsd-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "a01eabeda1ba619da5f44e1fe25e1f9627b4605f"
julia_version = "1.9.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "8a1dcc8a64a5601a27ed9db89d9fc15569c7c14d25c2ff90f30d1414152e88bf"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.0+0/GAP_pkg_juliainterface.v0.800.0.x86_64-unknown-freebsd-julia_version+1.9.0.tar.gz"
