[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "0650872f40d5762d1259f5c752f97d1b3dd8e5f2"
julia_version = "1.7.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "c2e2d4fe5ed2c0e82d196be65828b50acad75eb8f1a3ac21026448663bb2d752"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.301+0/GAP_pkg_juliainterface.v0.700.301.aarch64-apple-darwin-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "617ffd0771fa04235f72984789217df51d329bc5"
julia_version = "1.8.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "35570525cdcd2ea06e232f5a711a3ea7c7de773be8190da0c347a439e3374874"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.301+0/GAP_pkg_juliainterface.v0.700.301.aarch64-apple-darwin-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "c6b3ed5ddf8da9217f93959cb567e24e5ead2b0b"
julia_version = "1.9.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "b3863a9f660d83b9911c2e4755cf06188e5d7b78a9cf7cd3b06ff3d4743728a5"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.301+0/GAP_pkg_juliainterface.v0.700.301.aarch64-apple-darwin-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "e720762541fdcb5dcf5d2dfa94328c9fed473745"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "cfc4f5c38bf26197830c8384468a59d89ddbfe4b9c1a6b8ed67d56efa0c2427f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.301+0/GAP_pkg_juliainterface.v0.700.301.aarch64-linux-gnu-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "dc1d2d9e0d124efc5c0f3e9fc31d45d320b6e8fe"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "e8167291c7759835c74dea1ff7fab6c5a014a46917c61a0906e392bd475ba853"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.301+0/GAP_pkg_juliainterface.v0.700.301.aarch64-linux-gnu-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "538d2c66d22d066c8d1330ef33719276e0ec0ccd"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "f325bc0ff224eaf2912f05dad7382ba76268d87d572a5d2e685e9ef7ab09bf12"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.301+0/GAP_pkg_juliainterface.v0.700.301.aarch64-linux-gnu-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "4ec32ff1aa38110e67de64b56919c10e804cd79e"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "ba0d8eceaedbd122dafa741db9fd9732a017d289fe6130715097f02507808221"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.301+0/GAP_pkg_juliainterface.v0.700.301.aarch64-linux-gnu-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "3682e979b108218aa10f129a6b6d45f7cd99e75e"
julia_version = "1.6.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "1370e11de01e98726cea061ec90a83ceb147a76c92ba39c2d2906cd7f40c393d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.301+0/GAP_pkg_juliainterface.v0.700.301.aarch64-linux-musl-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "2bd2c2e82a36c28b17b0acf81c6ea895641048ca"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "0589b6cfd482029845331cefb3f50adbb462e74481377065c62b466f3321b71e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.301+0/GAP_pkg_juliainterface.v0.700.301.aarch64-linux-musl-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "4167eb074104fb12006b6f5371a38ae27a84011d"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "1f20d20d0ad361636f1038b6a5bd15abc7043e4e4ffc2de91d1b9ea9f2058050"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.301+0/GAP_pkg_juliainterface.v0.700.301.aarch64-linux-musl-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "83dcb1931f5e5ac35a31635e454c4993ef3de1f8"
julia_version = "1.9.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "d853dd152fa234ebcb2352e0047d5ed274c679384dad7a02732c19a71cda7595"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.301+0/GAP_pkg_juliainterface.v0.700.301.aarch64-linux-musl-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "67be55d17c45a4bf69d95bd0cb53ff25a02a7a87"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "b0355d06fd32843ba2447d7cf973afa097daed2d14c89394474a8c0963ec841d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.301+0/GAP_pkg_juliainterface.v0.700.301.powerpc64le-linux-gnu-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "07fdc1b57f15761734379ec3ebcb3554e8025c10"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "4a0ba1c77866872ecbae725a96ccb04059f208d5812373e24a72f110ed3ebc12"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.301+0/GAP_pkg_juliainterface.v0.700.301.powerpc64le-linux-gnu-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "3cabfe29fde4f271c119816c29ff0c855669bf59"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "84f9b038200d882494e5d6b0c2de306680c9d3acc0152a01d2eecfaff9241024"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.301+0/GAP_pkg_juliainterface.v0.700.301.powerpc64le-linux-gnu-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "e3b0d0ebc5027a63e6c6e7443a6c033a127a21c5"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "6392d4a831a270c4f0f4b82e997fb88807e3426d2c224d4aa42c753da2a4a964"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.301+0/GAP_pkg_juliainterface.v0.700.301.powerpc64le-linux-gnu-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "1fb3f8da222183d26eac85f69750c826f5ec8b34"
julia_version = "1.6.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "fe67f8fa71101a80750f4ae98bf2ae58b4ce11d67ea636327dc3cac41667def7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.301+0/GAP_pkg_juliainterface.v0.700.301.x86_64-apple-darwin-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "18778cd0de3c17fa0cbab16232c6984c08b4b09d"
julia_version = "1.7.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "a30c6a68ad88fd80b6beb2e2e943de8dc5b024dc5c38d8ea85d75a6c4f569772"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.301+0/GAP_pkg_juliainterface.v0.700.301.x86_64-apple-darwin-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "9222e578f22d2a805224488aae46071c647fa4d6"
julia_version = "1.8.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "1f95e35a792bf36b0cea7eb5fa34af1449f566a804bdebeb8b907842f9654b34"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.301+0/GAP_pkg_juliainterface.v0.700.301.x86_64-apple-darwin-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "c40a1a6fc73570b61481011b3a6fae8bed537473"
julia_version = "1.9.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "133c415f66e50e265a8eecd23451e04f3c348650dabb4b05c78788477df94a40"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.301+0/GAP_pkg_juliainterface.v0.700.301.x86_64-apple-darwin-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "6913649318f952a68c56f8e4a5952a9ea52e9adc"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "55298bc5e3586d46d24d9d4aea5ff48a9bba563fa02f3dcbc514203312b088e3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.301+0/GAP_pkg_juliainterface.v0.700.301.x86_64-linux-gnu-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "36d434992809a2c40fd1057bf35268a18a3d37c1"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "f8ea8f213db6a9282ffa59790afee47658e59f16895c219197420657e666fa91"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.301+0/GAP_pkg_juliainterface.v0.700.301.x86_64-linux-gnu-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "f8eb0dc34f1bd0748f65eed34a0afc2bc7160712"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "2f239051940424c0395dddb846518dd48e904c9e7b2bd3da3ef98f8fef361780"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.301+0/GAP_pkg_juliainterface.v0.700.301.x86_64-linux-gnu-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "fc98458b017a31f03f5677a602ea50fc9d839a2e"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "85a356cc2bd4a5060644238e92ad0c61104fc4dd312f5189e68f05ba7e436dcc"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.301+0/GAP_pkg_juliainterface.v0.700.301.x86_64-linux-gnu-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "1bba193eca047f9cc1f61ef2fc6ff0e0aaa18e2d"
julia_version = "1.6.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "2d7e32954f4790961b48bc8da3d215761da9d9a6a752c1ae0ba410dad9e73a45"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.301+0/GAP_pkg_juliainterface.v0.700.301.x86_64-linux-musl-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "35c81e00490180dc04dd84961b15db6582adbe6b"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "56b34b37caccf98da7cae8fa36533ba3fab1d6c3c84082b37d7751c866c54747"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.301+0/GAP_pkg_juliainterface.v0.700.301.x86_64-linux-musl-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "1cc11475d54984d9f0fdf9a0901d9a1d32c8e728"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "7efd6c53558a721e62fe75d1d7f86dc7aaca88e5917fadff8f7929c29950248d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.301+0/GAP_pkg_juliainterface.v0.700.301.x86_64-linux-musl-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "9ae4f06b30f79445ef018122d3a296332a284a68"
julia_version = "1.9.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "665aae8de93cd9b28a974b906f5a3b5ca4cc9e7e49c9d3e63f90ee82a0913976"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.301+0/GAP_pkg_juliainterface.v0.700.301.x86_64-linux-musl-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "1f1cf945a61f53ac236bcc3cf765dbeef3db5c83"
julia_version = "1.6.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "6783d65a4f1de6f38476d0a291beb76fabb453ecd5a4affb414d3882aa75b3a0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.301+0/GAP_pkg_juliainterface.v0.700.301.x86_64-unknown-freebsd-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "be080c76704535b83971d5d3b739792b6d39e9e2"
julia_version = "1.7.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "3e9081a545912aecd3ad30695bdecfd35772176104805fab392f3a48350e039a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.301+0/GAP_pkg_juliainterface.v0.700.301.x86_64-unknown-freebsd-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "09cc1019ba528622a32877fd088fba73087cd81d"
julia_version = "1.8.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "39c6163967f799b343db848d0b3d845896050383a3590881e3d4fca761a7c3c7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.301+0/GAP_pkg_juliainterface.v0.700.301.x86_64-unknown-freebsd-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "6067915b19d7352ef866c823beed6eacd72ba8e8"
julia_version = "1.9.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "286c1ac764b5dd893a578303367cbcaa7824b5abea5eb473c12b7d4110babdef"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.301+0/GAP_pkg_juliainterface.v0.700.301.x86_64-unknown-freebsd-julia_version+1.9.0.tar.gz"
