[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "ecc1ba9dea3bfadb52df046b310b62517fa8227e"
julia_version = "1.7.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "216678a29b03b73e3f5557bb9cfcc5b3fc8f301f47cd84686f00dea78e202a54"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+0/GAP_pkg_juliainterface.v0.700.100.aarch64-apple-darwin-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "e88df95e1247d5c7d8b90b7e54d7331e3a8ddcd2"
julia_version = "1.8.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "c883ea86528b612708c196e5891fe241c9d529d2afced6fded80818e2f726a43"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+0/GAP_pkg_juliainterface.v0.700.100.aarch64-apple-darwin-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "509ea3ff019cbc08cd52c6c2824949f3edd8ed84"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "5671d9e2648e60763bf9de848b3c48fe87c99442b34bd686c1f6d1b35d8a51fc"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+0/GAP_pkg_juliainterface.v0.700.100.aarch64-linux-gnu-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "40d0e5437ab09a85647889c655f5360126bb4f57"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "d183b70f45b5fb1c45c4a031a27089f07098852df93f89bd1c91f0387ba79116"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+0/GAP_pkg_juliainterface.v0.700.100.aarch64-linux-gnu-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "af5f3d4397dd9c8c12bf1acb0347501f3e29a07f"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "6215327cdcc01b998765ef9e8c4e21c20b8235944110e8e05a6b61cc7d36bbee"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+0/GAP_pkg_juliainterface.v0.700.100.aarch64-linux-gnu-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "1c3ceae74898b79ba862139cc18098ab2d5b9401"
julia_version = "1.6.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "394094b28cc40608c7da1dbde966f26f572149c581044fab2151c3d4ee440228"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+0/GAP_pkg_juliainterface.v0.700.100.aarch64-linux-musl-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "84a4db585e084b47aac0eb6ca7dc87e638cf0c2a"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "988327ab1e384660c2d73088b37b4fc3282f54f274dc0ee02f7d291016de1a1b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+0/GAP_pkg_juliainterface.v0.700.100.aarch64-linux-musl-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "c8e8fb03636b8b9940378c87065438f74bbd3919"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "671a29e37414126d548f5ec496bfb401a5c4f7a4791d80f22e99f879a6869bc8"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+0/GAP_pkg_juliainterface.v0.700.100.aarch64-linux-musl-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "748586402b4e2d59f9c8b216d312282bd0752d6a"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "31e55ffff1525d7e9c326c11fd9797d6384bbbdd9cba676fc09339ed587292ee"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+0/GAP_pkg_juliainterface.v0.700.100.powerpc64le-linux-gnu-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "7f4c2205b1163b8edc34db1a553a7e165104651d"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "129877f79f0bcbceae4ab149f1158f21e1c203c31fd3f7980bb99bca205cc736"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+0/GAP_pkg_juliainterface.v0.700.100.powerpc64le-linux-gnu-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "cecb552046332fb727a05d9f7b5b1bf540038688"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "175741a9f98da23bbbe8f4293ada42af9d360195bdcd9758d8c9958c94d11c24"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+0/GAP_pkg_juliainterface.v0.700.100.powerpc64le-linux-gnu-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "aa8838d6a41402b68bfb5b6f658df345f4ef04bd"
julia_version = "1.6.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "b6767db67c033c1755dd662098ce8dc77a1077173a4e770d8403aec51b41255b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+0/GAP_pkg_juliainterface.v0.700.100.x86_64-apple-darwin-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "2a1dccbdaf55c4cfc5f115b2b2698088102145d3"
julia_version = "1.7.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "f82939b1cfcf65bd687a1bcd25f7ad0ddfe5f958573081808223dac6d288fb12"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+0/GAP_pkg_juliainterface.v0.700.100.x86_64-apple-darwin-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "33a833866fc6bd058976d25f79a6e5e856e6afc0"
julia_version = "1.8.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "865b5c1ef81b14ce409ca2e6e4d15e5d73e0c7aff407ef7c0dd4617d91e87471"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+0/GAP_pkg_juliainterface.v0.700.100.x86_64-apple-darwin-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "a55496c2e7be04ced047fdf1e0a089fc9917d832"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "ba5b5b8d709a159dcc934fa537472a178465776c0215071b1193c2f4e07d4488"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+0/GAP_pkg_juliainterface.v0.700.100.x86_64-linux-gnu-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "516980fc46b9f4d356fedfdb803a9e8c47c5a69a"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "1619a67ce8c35e533b7cb745f839c135ce1a3a122ae4632d1ff37a49218a2358"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+0/GAP_pkg_juliainterface.v0.700.100.x86_64-linux-gnu-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "5b1b2ea81da5edde2fa7c91896b6dfc80d92e530"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "2146995320b6464d98971df21cb0b8d7bd969b6d6fd43833ae62d43b95ce9b77"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+0/GAP_pkg_juliainterface.v0.700.100.x86_64-linux-gnu-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "6ef9144f302539a08f737cc559ee3fa4017c184b"
julia_version = "1.6.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "b388e3b9678c8ab39990e0f5e8158687b369f6881bc00c61fdb123254c8a08bf"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+0/GAP_pkg_juliainterface.v0.700.100.x86_64-linux-musl-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "84344a0e461743f4fb0a88fca49605e2c59cd6c3"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "e471795d152e77e2f8d8767a81abc88716814eb5d99a27ebddc9d84104ad2e08"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+0/GAP_pkg_juliainterface.v0.700.100.x86_64-linux-musl-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "c72a56a69a15931695240eff5c881ff31badb9c6"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "faf274e0c80be7702aa9e52070942f657c5a996aee3143b1893a7fcab8207b4e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+0/GAP_pkg_juliainterface.v0.700.100.x86_64-linux-musl-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "fe85706561caf899200ea48f8019986ef8621093"
julia_version = "1.6.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "3759bd816579dbadd1721599b387ee4557ee4061d292afa33773d3305d18cd41"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+0/GAP_pkg_juliainterface.v0.700.100.x86_64-unknown-freebsd-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "093105f6779f5e121af857694c4f4f93e1eef27f"
julia_version = "1.7.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "9c92f50dc33e3edba69b9adef8dbea6a535fec6a85eb25346673f471f0b36cab"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+0/GAP_pkg_juliainterface.v0.700.100.x86_64-unknown-freebsd-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "6f489d1f1cbfa9ec72278309310c460c710bc9f6"
julia_version = "1.8.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "787cde82865752afe81b7280b049cbeb3a800b8e587b5041745a0f92058c96e4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.100+0/GAP_pkg_juliainterface.v0.700.100.x86_64-unknown-freebsd-julia_version+1.8.0.tar.gz"
