[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "5ae4490799ca390c5a8ea345cc10c0221c0e41bb"
julia_version = "1.10.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "f18f1202413047db27b0d0f265b7821c835a507c2bc12d0b74dbadc2fac6af87"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+0/GAP_pkg_juliainterface.v0.800.202.aarch64-apple-darwin-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "7ad4b75868db9e5ad08c70f61166ebe4a40b4dc8"
julia_version = "1.7.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "e8b761b8f62e30751a0771b1cbe1cf4eb15bc50f8a386f8637e2bd6acd86c2d0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+0/GAP_pkg_juliainterface.v0.800.202.aarch64-apple-darwin-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "1d3a5ee43cf314c759bb4a707df336cc39862d7b"
julia_version = "1.8.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "8eaf1607eee6041de6215afd6391fca909a79b1159026262d1aa3bc4d5f0dd3b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+0/GAP_pkg_juliainterface.v0.800.202.aarch64-apple-darwin-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "24e86e6e09dc977c719ecd8340816b4e1610e557"
julia_version = "1.9.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "bc2bcd77f9f07ff0489b6bdd7a18b4877f98bb7da8615cfe08b91507d502f22f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+0/GAP_pkg_juliainterface.v0.800.202.aarch64-apple-darwin-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "c6b15dafe3084616a7243fbfb0c7a9b09e3aa806"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "8578fa4ce4a64290290cabc616df7c3925c52d425acfa114d94343b266ddaec6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+0/GAP_pkg_juliainterface.v0.800.202.aarch64-linux-gnu-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "83aced1547cae23ce046f3cf91b1ca3376e50528"
julia_version = "1.6.3"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "5a829e62301c2d19dadf37309fc7d9bc49c3eb2f554f8ef43a35dc7602dca2ec"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+0/GAP_pkg_juliainterface.v0.800.202.aarch64-linux-gnu-julia_version+1.6.3.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "c4e0cf57267ec965af3faad489a7ee182260b768"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "6a5c92c149b11d980ac2cdc350a715a1cd38b95ce3c1105fdca362928be1272f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+0/GAP_pkg_juliainterface.v0.800.202.aarch64-linux-gnu-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "4bde17869f5ae5641a2f66e2017b9b03814145dc"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "d5299a4a3ae114d342f5c9a8b3b6d2d6b108fdccf5908ec9de4acc45f856b926"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+0/GAP_pkg_juliainterface.v0.800.202.aarch64-linux-gnu-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "a4465263336bfef0b87bf287ba121248a8a9e1c2"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "84cbcc93257fbf2798839ee30612137f084a3ffc42ae059c359fc8a56bb0360d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+0/GAP_pkg_juliainterface.v0.800.202.aarch64-linux-gnu-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "da66a52554a1ee9d7e183c3b54057dd5161094cf"
julia_version = "1.10.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "6e938de1ac32ba3d8b9d7674ac91404962f42125cc5cb751ab841e79d2b96814"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+0/GAP_pkg_juliainterface.v0.800.202.aarch64-linux-musl-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "76132bb696b23aff05ca7880961fcdfe5eb68568"
julia_version = "1.6.3"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "cdb379572817add10f45ce48f19f4c6e293605b6fee18b116588068fb06e7799"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+0/GAP_pkg_juliainterface.v0.800.202.aarch64-linux-musl-julia_version+1.6.3.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "93ecea46b6a98b3482deaae82abf7a105233255c"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "67cbbf9768672be428e13fd741fbdb8eb3c927fa940e29ee397cef94319cc6eb"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+0/GAP_pkg_juliainterface.v0.800.202.aarch64-linux-musl-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "c2284318af1b0e17503ee8da2699a520f5997c1b"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "8bb932c63b7067a4931fff8888a4802e7cdefb77b9e40ec9e1fc91d477439af7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+0/GAP_pkg_juliainterface.v0.800.202.aarch64-linux-musl-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "7f6259d805f2d1cb0c740465a9c1606cabed379c"
julia_version = "1.9.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "3876ddf1b5f56c61207f755b618244cafbde76a1279ebce42097fd472b326733"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+0/GAP_pkg_juliainterface.v0.800.202.aarch64-linux-musl-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "9fdf4e6c5f9a988ee99874cbe3f2ec97a8eab868"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "aa7dd05da6773018134dd0bb90971304f3d798cafac6d1ac781d2754df5ae230"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+0/GAP_pkg_juliainterface.v0.800.202.powerpc64le-linux-gnu-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "975f74496edd276b1c19eb44fea74efb49d83069"
julia_version = "1.6.3"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "69e03a6133cc350c4b6d64dc743acb42cabe232d850a273a801cf1b2e7857ca6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+0/GAP_pkg_juliainterface.v0.800.202.powerpc64le-linux-gnu-julia_version+1.6.3.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "a7ab57d0e299395b6c0491887054db9a383279af"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "c5bcbe16405e16773e58745eca74b379fd5965163325a7ab4501e2274bd0215f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+0/GAP_pkg_juliainterface.v0.800.202.powerpc64le-linux-gnu-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "2f5362b8519673b4158780a33edebb745146f744"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "cf8911ff71e9b5007f836563912ef2bd8a42624be18d003d7e3d16a13e67493b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+0/GAP_pkg_juliainterface.v0.800.202.powerpc64le-linux-gnu-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "d3042720f25e1b6e0e7b14fcc378ef563fc6a0d3"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "83f4c292a19b1768ba8f42c0f03e418f55d73ac7d9d05b5ddefa00136b39a9c8"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+0/GAP_pkg_juliainterface.v0.800.202.powerpc64le-linux-gnu-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "ba2f919496a73d6f0d2e4453be25dd9f35eee4b7"
julia_version = "1.10.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "bb53fc3837f8824275185c17b2721a7de285b3a67d5c0da37dce28c37dd00c3f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+0/GAP_pkg_juliainterface.v0.800.202.x86_64-apple-darwin-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "4382a6423fcf7dff1f7bbcb46a520df7e0d9e237"
julia_version = "1.6.3"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "56596f6e22a3aed0fe802305b09d064b15deab7206468c3a6705d6be27d1e050"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+0/GAP_pkg_juliainterface.v0.800.202.x86_64-apple-darwin-julia_version+1.6.3.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "d63fa2243ca714b7fa41588d1e412e60d4136ad2"
julia_version = "1.7.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "03c7b474a06f5d7593d6753e0642a85ebef443aeee7d6d402a91bda991e90ba8"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+0/GAP_pkg_juliainterface.v0.800.202.x86_64-apple-darwin-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "e3d91ab271bb3667f49ddee1b2000d124125953e"
julia_version = "1.8.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "ffda87b5543b350370ca8526d577d3b5d637eb3075f20a1447d4f0ae163f5ef3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+0/GAP_pkg_juliainterface.v0.800.202.x86_64-apple-darwin-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "11f33b32197c6541e84727d9147ca049c6abb6b1"
julia_version = "1.9.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "36a42985070da0803d2bfc576ccb94cb72eb5ac3f6638477ce8cddba24899763"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+0/GAP_pkg_juliainterface.v0.800.202.x86_64-apple-darwin-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "12ea22d3d913dc3898b0fce1a1c2bafeeaf63ad2"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "3ea6f73243d8931db39988e04ea63bc2d3831c2d110f0a44c0c0492bc120c1f0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+0/GAP_pkg_juliainterface.v0.800.202.x86_64-linux-gnu-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "775faf3c98f5ad9c91e39b9fcdf5dc03090f6fcc"
julia_version = "1.6.3"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "cffc262cd09d24eae3335f85f849e873a448bb2e079aad3c1543e006e1add905"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+0/GAP_pkg_juliainterface.v0.800.202.x86_64-linux-gnu-julia_version+1.6.3.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "8ac13574382917f80ce6997a936a7faf201356e3"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "5b5bc161e76d7412c636ddbbd878b908c392ab626cace2f6a8c2989a5315054c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+0/GAP_pkg_juliainterface.v0.800.202.x86_64-linux-gnu-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "985131c29aa1bc4c1eeb303198af124d4b98e2b3"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "30b5c1104646f76fed17e7520cc7688023f930c44aa8e56a82c0354f5308e2f2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+0/GAP_pkg_juliainterface.v0.800.202.x86_64-linux-gnu-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "b5810b5ccfc2bc70c60969e2bae37f98380409d4"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "d1dfe6640ca6d8b4d4c86282b26f9d821bc00b6cbeb70bc4f8b9a6a7e13a1637"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+0/GAP_pkg_juliainterface.v0.800.202.x86_64-linux-gnu-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "1deef46818874fa97315ec41cbc2193a39bbfa77"
julia_version = "1.10.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "d76c1979d0ee21679e17e02aa7de054bbe3535b016e12542a5f5a6626e78c288"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+0/GAP_pkg_juliainterface.v0.800.202.x86_64-linux-musl-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "d58475a276941e141c5ab9620116b0c502ccff3b"
julia_version = "1.6.3"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "c403e545b189610e45381fad311e16c5b5b3860a751348aef88bd542a69c0a66"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+0/GAP_pkg_juliainterface.v0.800.202.x86_64-linux-musl-julia_version+1.6.3.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "62edd739f1cd8a3fd54a0aa27724df8c3ac18df9"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "3c10ae2385beb475137ccf3ec8917d7b5ba9bddb5279394d9af2e4d2f247970c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+0/GAP_pkg_juliainterface.v0.800.202.x86_64-linux-musl-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "02c87ec9b32d38fe1ce227009a5de2aec271e60c"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "279d3c66d3391a870d765b18e54bc5edc191f54dc82c2225d28b8ac6b47156f0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+0/GAP_pkg_juliainterface.v0.800.202.x86_64-linux-musl-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "a404fdc9e620240d037d7bb151c15fdfade3dc5f"
julia_version = "1.9.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "1f459275286ae97b808eb5b20eedd5a126e760566e021e1320a2f336382b3c72"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+0/GAP_pkg_juliainterface.v0.800.202.x86_64-linux-musl-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "3c731ef1631e4b6ccce7107663a7badf9ab809bb"
julia_version = "1.10.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "ae63770cfee37d7a8c825811cfca83bcdb86272431ce105377d46bd7179fddaf"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+0/GAP_pkg_juliainterface.v0.800.202.x86_64-unknown-freebsd-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "e73690463574d75599a793363a6e9f3e4e3c4557"
julia_version = "1.6.3"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "a8596369b6a308810a0514a06a6c217a23c39fd52861507df7a70b851f387d59"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+0/GAP_pkg_juliainterface.v0.800.202.x86_64-unknown-freebsd-julia_version+1.6.3.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "addda3a9cb6b21fdb27c3fbb1cb8818643df849a"
julia_version = "1.7.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "cec65b3089e645f81a5f41849fedc1b99b02460277cbe4a5c2deb51063f97487"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+0/GAP_pkg_juliainterface.v0.800.202.x86_64-unknown-freebsd-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "fc5bbe085de54424fa092affe632ef0c19f7d8a5"
julia_version = "1.8.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "1911ed6f23c8ff6eb18d401bbcec4fc6eac0ceef7ae9e6462943fa7ceec52149"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+0/GAP_pkg_juliainterface.v0.800.202.x86_64-unknown-freebsd-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "0919b7d348b16e18708650a75a803b3a87ecc19b"
julia_version = "1.9.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "7e35086f43c79334dc7bdf5a2056105c9833946600a5fdde31319339db893922"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+0/GAP_pkg_juliainterface.v0.800.202.x86_64-unknown-freebsd-julia_version+1.9.0.tar.gz"
