[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "acc3f99414db7e8da703cd1044cf67f6fe4b7a2c"
julia_version = "1.7.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "5d6e5024c680f7b995b1b19aa6113e248bd8464e8ad596d65cd069eeb9bf8f30"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+0/GAP_pkg_juliainterface.v0.800.201.aarch64-apple-darwin-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "1bdd9615faaeea3b7a8347e5c9ff0a15686d403f"
julia_version = "1.8.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "3b0d5c709a0e6c5a8f3bd544a6edf6faa94202d731f31aa3fac7d4967bfa5f40"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+0/GAP_pkg_juliainterface.v0.800.201.aarch64-apple-darwin-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "716a7fad8bb2890cd82b2f5f25b06dc8ac81f2e5"
julia_version = "1.9.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "a7c6268c580de741d7967845d26c2084c1e61f47821f61e079e348f3c448c6c5"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+0/GAP_pkg_juliainterface.v0.800.201.aarch64-apple-darwin-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "bd3b6bc647e1bafbc814fedfaa1a05eceb71915e"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "a2bcdc1d49bde47199d4124ac352d89d652b6215792efccc15aef0c4e5fc94ee"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+0/GAP_pkg_juliainterface.v0.800.201.aarch64-linux-gnu-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "5d3a2d8eee1aa4407f2b2b8f0b4057d8be057f5e"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "ee4a043abdf6f5eef3e67955ff0f50516366fb9e1b5a5046e456123f2d5826cf"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+0/GAP_pkg_juliainterface.v0.800.201.aarch64-linux-gnu-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "9e3a0d868f3989d971334c3d5ef953d86a8bd293"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "26dfc98129f956475fe3f4c455cd382d6925c1b929783d78e942d0ff9aa69e68"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+0/GAP_pkg_juliainterface.v0.800.201.aarch64-linux-gnu-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "319d32312dd927f4a91c27b6253e876a1694bcf1"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "aefd23bd37d055da0d44aeecc7bf60397a68e291a45aa20a7b78afef67e512b6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+0/GAP_pkg_juliainterface.v0.800.201.aarch64-linux-gnu-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "32c15104f54b3e00919888c9909b2bb48eed8e8b"
julia_version = "1.6.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "4ef71532ff1fe5b1bd37c8e5bb76e6f891cb5ed0d2cab22d62c6fef6073a859e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+0/GAP_pkg_juliainterface.v0.800.201.aarch64-linux-musl-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "9e0ec70b6a22b7069d0e61ec1f58facaa7522635"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "7e9a8d6afd6576f8ba32dd75299c49ec8312bc4988393c8ea7d801a499ec4c5b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+0/GAP_pkg_juliainterface.v0.800.201.aarch64-linux-musl-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "de895428118cf617179a42199fe62438eab246dd"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "ce942615377c32e536deaf8826a7cd3f109d2158b71400b4edacdfc04b4d3240"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+0/GAP_pkg_juliainterface.v0.800.201.aarch64-linux-musl-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "848dd1c7d01334a1bd182c5c427fcba0e469159a"
julia_version = "1.9.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "911f58f0d0ba44f664fd8ce20737247a447db72f576282922b9269a49163e6ed"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+0/GAP_pkg_juliainterface.v0.800.201.aarch64-linux-musl-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "40f152b14ef301cc74d081f75f6c00257fc9e552"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "4b7618b2c429161788a0adae2606e5973df291e00d9d2171d47a3e2d615dad97"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+0/GAP_pkg_juliainterface.v0.800.201.powerpc64le-linux-gnu-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "6a824966c46dc9d1d0eaba847e11bf0dec3c85c8"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "d5cd2f6ce047f9c1214bd22baf143b6680c84a76ff35df1d679e5a6a9a6caaa4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+0/GAP_pkg_juliainterface.v0.800.201.powerpc64le-linux-gnu-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "b161769200c052ae59f7ceecd38ad610a6360c10"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "98894dba53d2792bcb6b3161135a2ae75090f7b244abe5f0cf2d8ff0850447d1"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+0/GAP_pkg_juliainterface.v0.800.201.powerpc64le-linux-gnu-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "f6ea924ae519aae6744b4e79367190dc5e48e136"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "ad69d95245010c194d56a4d57319084060850da9744d2ac3a2e43d6273d671cc"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+0/GAP_pkg_juliainterface.v0.800.201.powerpc64le-linux-gnu-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "b6ffb682a5c87ffab46c69854f1b7716376bc6d9"
julia_version = "1.6.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "d486c6db10b6b2de9cb6b3708503a88aab091b84958dfcd8bc4151a8520df422"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+0/GAP_pkg_juliainterface.v0.800.201.x86_64-apple-darwin-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "e250a88c24e51dcdd4cf74168a74a4b20cb19946"
julia_version = "1.7.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "7f2a5b208dfb159595979c7fff011343de25dec2d9b7494be0d998303a1b40de"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+0/GAP_pkg_juliainterface.v0.800.201.x86_64-apple-darwin-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "1efd33fd830df62e54d613687f0aa0cf63b102f7"
julia_version = "1.8.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "f97f793126674afde5737dfe318cc7723580083aad7345ce334c1f23201337a9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+0/GAP_pkg_juliainterface.v0.800.201.x86_64-apple-darwin-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "b3d7933bc2c6c5639f94b820633d7b56dea67b78"
julia_version = "1.9.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "8f09585488741fccda33a7b0c283e8d5c99de2960252fa1f6edcaa3de096e681"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+0/GAP_pkg_juliainterface.v0.800.201.x86_64-apple-darwin-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "57fe5a49d0c87bb98e0c39095bb3d54df458fda8"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "b29b89bfc5a6c94830b29d3bcd7bea6d322f621d0f00b7fba27459014e8fdef7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+0/GAP_pkg_juliainterface.v0.800.201.x86_64-linux-gnu-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "1de9860fb3384c6054253f8caf4ec6e3b851b3c0"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "16d0b198c176eb725253e07dc091c631741ea0d51f2e7b74aa8179093461cf92"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+0/GAP_pkg_juliainterface.v0.800.201.x86_64-linux-gnu-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "5ce7848216933f604c6e0d7ce6120500d61cf5c5"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "d4a7a8220da3ccce884f48e620909ecb5d7b25014d1393adcc2647cf9a2d4cd4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+0/GAP_pkg_juliainterface.v0.800.201.x86_64-linux-gnu-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "153e0de4e334c65003fe70493895271170158c2e"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "ea140dbd626ca79126d6c18f49718111e9029626d4b7c5f944b2fa355ae4fdfa"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+0/GAP_pkg_juliainterface.v0.800.201.x86_64-linux-gnu-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "321f0cfdd3ad19133bd8d23c8bd135147e72ccdb"
julia_version = "1.6.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "ebad254bcfdc6c7f3968ec8c37908e05cae2269e278e7013b292391d3857d33c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+0/GAP_pkg_juliainterface.v0.800.201.x86_64-linux-musl-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "6ea028ac63d8767da674a60808e9da498f6b2a25"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "df07a28985203d69a08b1bf48e7320e6ae6805f3c248ccbb0681c0fc20ce0a0d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+0/GAP_pkg_juliainterface.v0.800.201.x86_64-linux-musl-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "895de54c9e19f385815ff92121c5224119213e96"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "261add284892d83be73d3af4fac49f815a63d729751feafdd4d6fdaacf8a7478"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+0/GAP_pkg_juliainterface.v0.800.201.x86_64-linux-musl-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "9d2e33eb14eadd006f41f5119286dde4c66101cb"
julia_version = "1.9.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "57551754bb796323c824cfadddde4ae75d9191af33654a39760915afa3766469"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+0/GAP_pkg_juliainterface.v0.800.201.x86_64-linux-musl-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "e5ab24c452e29d6898f997bc030b98ce08deb381"
julia_version = "1.6.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "fd4d42a133da82b08aa80a5e8563aaf17e49ab2100b682e66d7955cd72dacfb5"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+0/GAP_pkg_juliainterface.v0.800.201.x86_64-unknown-freebsd-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "dacef326fa01ec5ea46d11abc46764ac310a2a34"
julia_version = "1.7.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "897152fd8ae5883296e2fc6c7770b2e912699870d0123cacd1cfdf9a361d080e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+0/GAP_pkg_juliainterface.v0.800.201.x86_64-unknown-freebsd-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "6706f47fe9308d3af59861a4617f711228eb2cd5"
julia_version = "1.8.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "41ac5cb27ddef3d5a195c5928ee8b61e5ea59030fa560572186e2e7515c426da"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+0/GAP_pkg_juliainterface.v0.800.201.x86_64-unknown-freebsd-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "ee8b40e7465f8849c90dff77259c0099d744124c"
julia_version = "1.9.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "c7d43ebac02978b914b8d78418c5db9ae1b11f8d32d337dcc737bea205a53b0d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+0/GAP_pkg_juliainterface.v0.800.201.x86_64-unknown-freebsd-julia_version+1.9.0.tar.gz"
