[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "58cacb99f63c114cc8566a6fcd60dc175929a5a0"
julia_version = "1.7.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "d2c54bf44b90511ad64f2e73d9b342be5f9f85e359b4d2f9752027d0c378567d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+1/GAP_pkg_juliainterface.v0.800.201.aarch64-apple-darwin-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "7eb04b7eca443e4d038a52532a3c6c2b49845178"
julia_version = "1.8.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "91fae224c75c65ea6dfc2f037a0e613f293473eae3d56af1825cb2206743241d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+1/GAP_pkg_juliainterface.v0.800.201.aarch64-apple-darwin-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "9493c99f15b6d2ac0d6e86d038fe312f5aaf6149"
julia_version = "1.9.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "7340b4d24e8a7de99fc3ddbed04211014626afe0fe650aa8a6c2800db96b8184"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+1/GAP_pkg_juliainterface.v0.800.201.aarch64-apple-darwin-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "1081100ca318daab500704dc60c77e3eb126e640"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "f510b8747761e4ef529b59661ddd37983aa002f08d6476dfad78d39e4635cff4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+1/GAP_pkg_juliainterface.v0.800.201.aarch64-linux-gnu-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "2b316c41130810a3326d269072f26db295ad96e8"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "18c4e24bc237cb14b34c306976568b3e12da296a0b53a13cda3070d7a1691d58"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+1/GAP_pkg_juliainterface.v0.800.201.aarch64-linux-gnu-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "a68da90154e671874f7f71e1032e6323d7c2ac79"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "c615e1ff359fa90221594e039a278ba2925410924e01a92d111a9a9ff4eef79e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+1/GAP_pkg_juliainterface.v0.800.201.aarch64-linux-gnu-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "095731597335d662ef675ae01abab1cdb913f87f"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "6044a37c45ba8bcf743e4d2d5bfa1a3a080288535fa43790178ec5b4b2410f17"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+1/GAP_pkg_juliainterface.v0.800.201.aarch64-linux-gnu-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "8a884dbbe115f24b767db93f06bb38515cb89f4f"
julia_version = "1.6.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "cffaa7bbb837f21878ab19377620fe351783e2c9366b157f19f90042523d003f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+1/GAP_pkg_juliainterface.v0.800.201.aarch64-linux-musl-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "a74e93292448876705f6df101d14e1fa97243bed"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "8d954b00f5cfcdabc0ab199ad18242b60d1d33820923705d5e35e108fc02109e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+1/GAP_pkg_juliainterface.v0.800.201.aarch64-linux-musl-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "3f49e482ae4b34a88401ec6d39244a5afceb0ddd"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "682fc647e5b2e23b8ad25d0e59db148991e8e962027a282b74845d2d30c52ab3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+1/GAP_pkg_juliainterface.v0.800.201.aarch64-linux-musl-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "32e6d0bf2fdeb503bbd4ea1949461a8d1a6c0a8e"
julia_version = "1.9.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "65dfa010db3dfe906a12821998f0af8ae2f021712cdd7d0d43984cabb6c8236e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+1/GAP_pkg_juliainterface.v0.800.201.aarch64-linux-musl-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "352849bcb030b50b24e803989178d434bb5750c7"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "15934892017dac30b5fd8a5b86004ec5fc219bd86b7edf2049e7b4e7df074b37"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+1/GAP_pkg_juliainterface.v0.800.201.powerpc64le-linux-gnu-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "6d803e3a39916c5a533407f2ebe5b2699bb8209d"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "071ddd3c227d6af6fa8f29edc4d36d1989bda1559392a728c985f969c7fc1e0f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+1/GAP_pkg_juliainterface.v0.800.201.powerpc64le-linux-gnu-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "62b32976348c1f3e3b1b43054fc11e50e7d8860f"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "bbee723116468b6d3963a050388c500a5f77e9dfed85efbe072e14a2382e89ca"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+1/GAP_pkg_juliainterface.v0.800.201.powerpc64le-linux-gnu-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "85a567cbf8d4547bad9f5726e48d31e95d430b19"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "8e79acdb2a1cb4c2279a2fb61f27e15d8d858564b1a6c83a594284bc36c817ba"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+1/GAP_pkg_juliainterface.v0.800.201.powerpc64le-linux-gnu-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "be058d975e0dd31ec3a536466d4c0eb5624c90d3"
julia_version = "1.6.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "e51e2c3bc09b21b4a1ef45b7d753a1f871a5a4411df7703cfcfacb3cac9268bd"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+1/GAP_pkg_juliainterface.v0.800.201.x86_64-apple-darwin-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "8e63c2e74e2738a7dc74226387b1b1c87034975f"
julia_version = "1.7.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "b5379f74571a39431a910d0f83672ab5d0446941dd7e05b7a9ce9ec10460aa61"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+1/GAP_pkg_juliainterface.v0.800.201.x86_64-apple-darwin-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "d550c716c0eeacc7f496bc822445b86978a643b2"
julia_version = "1.8.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "a19d989df6a343d0309f1bef965453cd960684c0459730454d2f25ccc564f73c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+1/GAP_pkg_juliainterface.v0.800.201.x86_64-apple-darwin-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "d34aebefdf4641027f6658679813e923f1160a87"
julia_version = "1.9.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "055726cfb7c0cff67d60306bf5fea890e5e9b31fd7eae661fad8d59e863a6691"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+1/GAP_pkg_juliainterface.v0.800.201.x86_64-apple-darwin-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "254618f460fae5c61181f302da32aaf725ba80b0"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "4da13092aeb04b8b4f7653b395bc524ea6f191919cfb7da2db6be846e559d082"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+1/GAP_pkg_juliainterface.v0.800.201.x86_64-linux-gnu-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "2e36ab518d2846485f77595775b94bc85a1185d6"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "dd954e7f0e9c7ee6c14155f3d76b6387334a8c0d4db58da1ad177e90929f28a0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+1/GAP_pkg_juliainterface.v0.800.201.x86_64-linux-gnu-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "3178f2673dfbca96a1b950d66be9d4b60f1268f6"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "4c9bffce9e4f661395cc3e3fa28e4ae5e4de692ed4fb323edfcdc57ddc2deb69"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+1/GAP_pkg_juliainterface.v0.800.201.x86_64-linux-gnu-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "7308c147ecc88273d4f5014b82fca00971ad4ad7"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "aa7d9574954950cf15e757d708bd7a6eb33a03ee1a7cb20deb5e77be36a1825b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+1/GAP_pkg_juliainterface.v0.800.201.x86_64-linux-gnu-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "0d7c2003af01e8f5a44a56f6c382ce2ade441323"
julia_version = "1.6.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "01692657535f718f5a1ebd3e7c290b4a35a6ab581752b9e03b71f45ae8b72d05"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+1/GAP_pkg_juliainterface.v0.800.201.x86_64-linux-musl-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "4919a74f48363b58f22d297c8a36884a935384fd"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "5fe60ffcb5b925063e221d57b0388595bce60ffb740d4d1683a7f673b3b9d409"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+1/GAP_pkg_juliainterface.v0.800.201.x86_64-linux-musl-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "923a90c3f09a0e64413e50b186280dfd449e8956"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "b31b091ed7215b72bc602bd70fd10cdadbfa8ead53858f0d0157d9332cfed2a4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+1/GAP_pkg_juliainterface.v0.800.201.x86_64-linux-musl-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "6314387c167f1836127286d6974f6c6bc052d5d2"
julia_version = "1.9.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "aee5c772a25cbba0f5db1c3476084d91868acaafac6b5b8ad9c0e52eefbf511b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+1/GAP_pkg_juliainterface.v0.800.201.x86_64-linux-musl-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "e73690463574d75599a793363a6e9f3e4e3c4557"
julia_version = "1.6.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "a8596369b6a308810a0514a06a6c217a23c39fd52861507df7a70b851f387d59"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+1/GAP_pkg_juliainterface.v0.800.201.x86_64-unknown-freebsd-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "7913638c1b690fa44d74247e32c58d945b4ef534"
julia_version = "1.7.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "3724a85be22b61c3f6443dc0c82a24328a85e2204360be99b34a04a4e413de16"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+1/GAP_pkg_juliainterface.v0.800.201.x86_64-unknown-freebsd-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "fc5bbe085de54424fa092affe632ef0c19f7d8a5"
julia_version = "1.8.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "1911ed6f23c8ff6eb18d401bbcec4fc6eac0ceef7ae9e6462943fa7ceec52149"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+1/GAP_pkg_juliainterface.v0.800.201.x86_64-unknown-freebsd-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "84a4602ac7f771a7df67bdda22a8c541aa449fc8"
julia_version = "1.9.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "8dc712fc96b8ba39b0deb0ddefb80da31ea35d6e70304e601c8d9a9a7141be83"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.201+1/GAP_pkg_juliainterface.v0.800.201.x86_64-unknown-freebsd-julia_version+1.9.0.tar.gz"
