[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "ae8f5b971204f492def1621f2a2935ac81101fc8"
julia_version = "1.7.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "06b5c0d4a7031e45fe5e38a68bf33b38f903c3077d313df2da1fdf73948cc970"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.300+0/GAP_pkg_juliainterface.v0.700.300.aarch64-apple-darwin-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "a35bda6d510882fbd0e0862bedcd355116be930f"
julia_version = "1.8.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "7647f9426831c38ae11e3159bc1a2959011e58a53dd359857e512481a043c532"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.300+0/GAP_pkg_juliainterface.v0.700.300.aarch64-apple-darwin-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "32585be33124bacc05e7316b73c5929737982f47"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "3011fa3d31c8d085fb89d58fe1b620ed7edc7a7224a20ac31aa34cefe6582150"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.300+0/GAP_pkg_juliainterface.v0.700.300.aarch64-linux-gnu-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "41d0d92c1f91c97b4bad899a868b22b20e4f2c22"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "288b7b51b55c3b5ab73f57a19c797126436d136f822405b93f793983dc3aacf9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.300+0/GAP_pkg_juliainterface.v0.700.300.aarch64-linux-gnu-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "7e1246e4fb57dabfd87aeb8499bbb1488d89f86d"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "c8ba8cc1389414e94e0a701b456fbf97c76691bba37c298fb3c987fc25579cb2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.300+0/GAP_pkg_juliainterface.v0.700.300.aarch64-linux-gnu-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "8eeb6faddb389faa47df44e544c8b85a4145a8cc"
julia_version = "1.6.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "553e88098b9b9f070fd36e7a36417ca28a3301f57a631691b76f2e5a1531a08e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.300+0/GAP_pkg_juliainterface.v0.700.300.aarch64-linux-musl-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "f396e6b83fb476573d19082f45b8cc8f5f819bf9"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "58be3b3a4520b1a10f162fa96a25cedc49f4923aff8d1d9136abc6134107da40"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.300+0/GAP_pkg_juliainterface.v0.700.300.aarch64-linux-musl-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "8612784a0271fe899644929aac6080f1cc704afa"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "eb01feb856fe3a734af29b54f4a9d434a5da67ce4bb4b33782b644f806d3a58e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.300+0/GAP_pkg_juliainterface.v0.700.300.aarch64-linux-musl-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "f0e42d708c70c56890c2766c370d0ee2f34c5706"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "6836997c2da4a2fabbe6351109fabe2e1e69257d8b25fe69a0be54f39510c512"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.300+0/GAP_pkg_juliainterface.v0.700.300.powerpc64le-linux-gnu-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "4889ef519824c65f3fdf0fe23838c5e031e396cd"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "4c49b3655756b212ace1bbd4b964b1cc00fe0d7158e8661ec7bd58ff5b18ae9c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.300+0/GAP_pkg_juliainterface.v0.700.300.powerpc64le-linux-gnu-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "803d9a19928d41f2690a1813bd119646f278fb3c"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "c3abb4260b3e1ef70d96bb215fa227e017e2a0bb1e2b6d7d8471e832aa559efe"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.300+0/GAP_pkg_juliainterface.v0.700.300.powerpc64le-linux-gnu-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "2d2e21d0b0361a598a550a47b96598227587e89d"
julia_version = "1.6.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "045f62f12c010a85a112762a98a067ead66fd9ce4c4440a41c44a1ff8a11322e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.300+0/GAP_pkg_juliainterface.v0.700.300.x86_64-apple-darwin-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "761876f6c68ef36631e81f8803b30c9954dcc71d"
julia_version = "1.7.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "e5a26248c281c3c83305598de5e141ed9c63a6964b69bffe7b5da9a09a3ec161"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.300+0/GAP_pkg_juliainterface.v0.700.300.x86_64-apple-darwin-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "bae205846085dbfff381e756e11e168dd8c18d83"
julia_version = "1.8.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "47b37dd379dee8d5ea2381cf464d97ff98acdec26841ae1b24b515ecdef849c4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.300+0/GAP_pkg_juliainterface.v0.700.300.x86_64-apple-darwin-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "3bf47e54f6ab5aec612d38e1809478afcc095f0f"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "616898868fd7b0430d40a45641d8429a38a8a00203fa18d620c774d30016d4e7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.300+0/GAP_pkg_juliainterface.v0.700.300.x86_64-linux-gnu-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "f38cb8ac15930d5b717ac665df3c412b83257bd2"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "8ce99be104523897321d957d5eca24fcb38776a57d18d440ca9381e311771f8a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.300+0/GAP_pkg_juliainterface.v0.700.300.x86_64-linux-gnu-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "fc2b470d39cce110d61742bd17a14fdc218be36a"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "742b9a27ca7557f43b85246d06a4d4257169178396ee010e229dab81e3442e99"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.300+0/GAP_pkg_juliainterface.v0.700.300.x86_64-linux-gnu-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "8ba604b2034f00fc1497c60a101e10c32ee59df0"
julia_version = "1.6.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "3fbac45f5355fc43341273883ffc162abdb6a2bdf7a06054bfd2715e23b94281"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.300+0/GAP_pkg_juliainterface.v0.700.300.x86_64-linux-musl-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "1e8929e88bda64cc9c2812e94081d07cc18bb653"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "f0efdaee2c99b3211e7c333eb8a42af56bf33893f9fadc5245495f08e774f3f3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.300+0/GAP_pkg_juliainterface.v0.700.300.x86_64-linux-musl-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "81d588f54b6f31d6fd5a7addd91084e64e3f18d9"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "e045e8834b815bf4a5d12b3b07e6115b8997dff1e2b627341856fe3a1eafc93f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.300+0/GAP_pkg_juliainterface.v0.700.300.x86_64-linux-musl-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "37ddd490583f7fe82103b9062359f7904f01b6ec"
julia_version = "1.6.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "e18f094cb06a365df2c0571d913933bea218b479ca40dbb19859d63fddb7bb2f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.300+0/GAP_pkg_juliainterface.v0.700.300.x86_64-unknown-freebsd-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "1c44d9f4b1c025b77065dd2e69eba239c7407405"
julia_version = "1.7.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "4170b430e5c7abb96fcf9090d46b3929800ffe9909730d23ca1f83424ca6233d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.300+0/GAP_pkg_juliainterface.v0.700.300.x86_64-unknown-freebsd-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "990a940ce414a4b3daecc6e39e5074b11ac8cba5"
julia_version = "1.8.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "af66dfe654dda785b7cf3363a660b85e20ef6a2cb4eacf0c487c6b95d6a4531c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.300+0/GAP_pkg_juliainterface.v0.700.300.x86_64-unknown-freebsd-julia_version+1.8.0.tar.gz"
