[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "a1f23531bb635b60775d4a26e0def3c342df4bc0"
julia_version = "1.10.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "813b5639c325d7eee24489930258cb8437a4ddda68b8cce67e4f4ac8dd7c9d78"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+3/GAP_pkg_juliainterface.v0.800.202.aarch64-apple-darwin-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "7ad4b75868db9e5ad08c70f61166ebe4a40b4dc8"
julia_version = "1.7.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "e8b761b8f62e30751a0771b1cbe1cf4eb15bc50f8a386f8637e2bd6acd86c2d0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+3/GAP_pkg_juliainterface.v0.800.202.aarch64-apple-darwin-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "1d3a5ee43cf314c759bb4a707df336cc39862d7b"
julia_version = "1.8.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "8eaf1607eee6041de6215afd6391fca909a79b1159026262d1aa3bc4d5f0dd3b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+3/GAP_pkg_juliainterface.v0.800.202.aarch64-apple-darwin-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "24e86e6e09dc977c719ecd8340816b4e1610e557"
julia_version = "1.9.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "bc2bcd77f9f07ff0489b6bdd7a18b4877f98bb7da8615cfe08b91507d502f22f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+3/GAP_pkg_juliainterface.v0.800.202.aarch64-apple-darwin-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "79dd007a99e146ae5620139cf688535ee321c936"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "4e7e579a6f185bb5775f3dd4f242519853bb10c7a97c389d6b27a87c71c3e92a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+3/GAP_pkg_juliainterface.v0.800.202.aarch64-linux-gnu-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "83aced1547cae23ce046f3cf91b1ca3376e50528"
julia_version = "1.6.3"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "5a829e62301c2d19dadf37309fc7d9bc49c3eb2f554f8ef43a35dc7602dca2ec"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+3/GAP_pkg_juliainterface.v0.800.202.aarch64-linux-gnu-julia_version+1.6.3.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "c4e0cf57267ec965af3faad489a7ee182260b768"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "6a5c92c149b11d980ac2cdc350a715a1cd38b95ce3c1105fdca362928be1272f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+3/GAP_pkg_juliainterface.v0.800.202.aarch64-linux-gnu-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "4bde17869f5ae5641a2f66e2017b9b03814145dc"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "d5299a4a3ae114d342f5c9a8b3b6d2d6b108fdccf5908ec9de4acc45f856b926"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+3/GAP_pkg_juliainterface.v0.800.202.aarch64-linux-gnu-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "1db775016ecad53f9255e6d1696220a863a28396"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "ca5c08ab7a8646454c00ec6f22d5a17b5131e337ed311617d45e05f45accb076"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+3/GAP_pkg_juliainterface.v0.800.202.aarch64-linux-gnu-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "27ca7d0b4d5dea50b2dd05f6aa89d3b392f86dc6"
julia_version = "1.10.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "f093d893a03912a467381ff562a191c4ef59ad3b36a02ea9d82948668131a9bd"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+3/GAP_pkg_juliainterface.v0.800.202.aarch64-linux-musl-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "76132bb696b23aff05ca7880961fcdfe5eb68568"
julia_version = "1.6.3"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "cdb379572817add10f45ce48f19f4c6e293605b6fee18b116588068fb06e7799"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+3/GAP_pkg_juliainterface.v0.800.202.aarch64-linux-musl-julia_version+1.6.3.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "93ecea46b6a98b3482deaae82abf7a105233255c"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "67cbbf9768672be428e13fd741fbdb8eb3c927fa940e29ee397cef94319cc6eb"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+3/GAP_pkg_juliainterface.v0.800.202.aarch64-linux-musl-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "c2284318af1b0e17503ee8da2699a520f5997c1b"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "8bb932c63b7067a4931fff8888a4802e7cdefb77b9e40ec9e1fc91d477439af7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+3/GAP_pkg_juliainterface.v0.800.202.aarch64-linux-musl-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "df7be0ece809d27028e2fd545273a50e81b56d5f"
julia_version = "1.9.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "d6ff70772c8066eaf83173eb403805eac12d94305115257c855b228122d11ff2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+3/GAP_pkg_juliainterface.v0.800.202.aarch64-linux-musl-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "039e54a3bcd30dc496a7c624c24865dbe9b00aba"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "b98dbc69cbfc2862d7e643f5e4145f0cfcfb48de62295442b235b7a6459b75d8"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+3/GAP_pkg_juliainterface.v0.800.202.powerpc64le-linux-gnu-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "975f74496edd276b1c19eb44fea74efb49d83069"
julia_version = "1.6.3"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "69e03a6133cc350c4b6d64dc743acb42cabe232d850a273a801cf1b2e7857ca6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+3/GAP_pkg_juliainterface.v0.800.202.powerpc64le-linux-gnu-julia_version+1.6.3.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "a7ab57d0e299395b6c0491887054db9a383279af"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "c5bcbe16405e16773e58745eca74b379fd5965163325a7ab4501e2274bd0215f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+3/GAP_pkg_juliainterface.v0.800.202.powerpc64le-linux-gnu-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "2f5362b8519673b4158780a33edebb745146f744"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "cf8911ff71e9b5007f836563912ef2bd8a42624be18d003d7e3d16a13e67493b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+3/GAP_pkg_juliainterface.v0.800.202.powerpc64le-linux-gnu-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "28f89b21ece61248d5be1a19e5360a04e697420a"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "22edad7bbb6f6c1c9771e7d40bca077e3c791fa7e1df6d5efee2479500585326"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+3/GAP_pkg_juliainterface.v0.800.202.powerpc64le-linux-gnu-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "2911a50383124172ee2feff4c615b0381e7971ca"
julia_version = "1.10.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "766ecaeccf1b0e03cd9ad73f55f9499df11deecf799c698a44ce47c51e51a0f7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+3/GAP_pkg_juliainterface.v0.800.202.x86_64-apple-darwin-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "4382a6423fcf7dff1f7bbcb46a520df7e0d9e237"
julia_version = "1.6.3"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "56596f6e22a3aed0fe802305b09d064b15deab7206468c3a6705d6be27d1e050"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+3/GAP_pkg_juliainterface.v0.800.202.x86_64-apple-darwin-julia_version+1.6.3.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "d63fa2243ca714b7fa41588d1e412e60d4136ad2"
julia_version = "1.7.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "03c7b474a06f5d7593d6753e0642a85ebef443aeee7d6d402a91bda991e90ba8"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+3/GAP_pkg_juliainterface.v0.800.202.x86_64-apple-darwin-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "e3d91ab271bb3667f49ddee1b2000d124125953e"
julia_version = "1.8.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "ffda87b5543b350370ca8526d577d3b5d637eb3075f20a1447d4f0ae163f5ef3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+3/GAP_pkg_juliainterface.v0.800.202.x86_64-apple-darwin-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "11f33b32197c6541e84727d9147ca049c6abb6b1"
julia_version = "1.9.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "36a42985070da0803d2bfc576ccb94cb72eb5ac3f6638477ce8cddba24899763"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+3/GAP_pkg_juliainterface.v0.800.202.x86_64-apple-darwin-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "43cb68ba023d23b7ad9fc746de56cbb241d43ba2"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "73953e7014799b1d494d2002802216797b2453c9cb36a0a588443ba1e6d118a3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+3/GAP_pkg_juliainterface.v0.800.202.x86_64-linux-gnu-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "775faf3c98f5ad9c91e39b9fcdf5dc03090f6fcc"
julia_version = "1.6.3"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "cffc262cd09d24eae3335f85f849e873a448bb2e079aad3c1543e006e1add905"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+3/GAP_pkg_juliainterface.v0.800.202.x86_64-linux-gnu-julia_version+1.6.3.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "8ac13574382917f80ce6997a936a7faf201356e3"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "5b5bc161e76d7412c636ddbbd878b908c392ab626cace2f6a8c2989a5315054c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+3/GAP_pkg_juliainterface.v0.800.202.x86_64-linux-gnu-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "985131c29aa1bc4c1eeb303198af124d4b98e2b3"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "30b5c1104646f76fed17e7520cc7688023f930c44aa8e56a82c0354f5308e2f2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+3/GAP_pkg_juliainterface.v0.800.202.x86_64-linux-gnu-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "154855ac54d7957cca4fcc5539833242ebd9643a"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "4af86e45af013b5dd845efdeb1255e20e2722e98fd8e5a013d42619575fcaced"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+3/GAP_pkg_juliainterface.v0.800.202.x86_64-linux-gnu-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "c42f776848b1b9a28a71badd6e958ad6b1184f86"
julia_version = "1.10.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "e7d6316cc0592859e8e6f392d171859dcec368d8c53904942ea8d1cf0fe68f74"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+3/GAP_pkg_juliainterface.v0.800.202.x86_64-linux-musl-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "d58475a276941e141c5ab9620116b0c502ccff3b"
julia_version = "1.6.3"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "c403e545b189610e45381fad311e16c5b5b3860a751348aef88bd542a69c0a66"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+3/GAP_pkg_juliainterface.v0.800.202.x86_64-linux-musl-julia_version+1.6.3.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "62edd739f1cd8a3fd54a0aa27724df8c3ac18df9"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "3c10ae2385beb475137ccf3ec8917d7b5ba9bddb5279394d9af2e4d2f247970c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+3/GAP_pkg_juliainterface.v0.800.202.x86_64-linux-musl-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "02c87ec9b32d38fe1ce227009a5de2aec271e60c"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "279d3c66d3391a870d765b18e54bc5edc191f54dc82c2225d28b8ac6b47156f0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+3/GAP_pkg_juliainterface.v0.800.202.x86_64-linux-musl-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "64b75519c84b88ddc232c6dcc1b42fd2a93c2f79"
julia_version = "1.9.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "714ccc50f9a7ed3c4cb253759222a2baf174179079c515a404b631ef054a974e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+3/GAP_pkg_juliainterface.v0.800.202.x86_64-linux-musl-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "7bf23a17ccefc0e9de5f925f9a771a9e8ef929d6"
julia_version = "1.10.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "cd9abf7955f65776a6e6a70f4d3fa9255a4657a5d06e179c9bc2055ecdc5c2cf"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+3/GAP_pkg_juliainterface.v0.800.202.x86_64-unknown-freebsd-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "3949876a14403b45f24bee761ab31b18beddc474"
julia_version = "1.6.3"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "3ba608a90e8c07dddd921f92975a0ea20951b27d3e5eeb537116eba66e1c5ccf"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+3/GAP_pkg_juliainterface.v0.800.202.x86_64-unknown-freebsd-julia_version+1.6.3.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "3aaef4f0f408c75cd3e7bd1ce764ce3018ff8f4e"
julia_version = "1.7.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "4d3d3122aa732e5fd2dce9a3283098a7fb8ca082effc7400f9586f938c57b828"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+3/GAP_pkg_juliainterface.v0.800.202.x86_64-unknown-freebsd-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "29e07bd4f4afef6f25e273aaf2133de4958b50af"
julia_version = "1.8.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "f346abfddf5433996833a8e926bca38819e5e2ee6bb379c5362a4472ff3f90d2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+3/GAP_pkg_juliainterface.v0.800.202.x86_64-unknown-freebsd-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "d1cf13ec17cd4741be38e3009c9d9c479db77752"
julia_version = "1.9.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "6408f71c5cb197e3bb2ce09e72c3a06e832f41d1dc403918483f7dabf42d43cb"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.202+3/GAP_pkg_juliainterface.v0.800.202.x86_64-unknown-freebsd-julia_version+1.9.0.tar.gz"
