[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "87d6a987ebb56e9a145421fd931b816f97d2fbac"
julia_version = "1.7.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "f22db65af6dde893db3b1170124190c01e5d0bd4d6116b93af96680808d6a9c1"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.0+1/GAP_pkg_juliainterface.v0.700.0.aarch64-apple-darwin-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "dd1806632da0bcf83259bf5f0c337955af5bdc08"
julia_version = "1.8.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "a44e8aaa8b00fdca99bb58ae9dc66e27044ca59f74d61db158d2466c105fe280"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.0+1/GAP_pkg_juliainterface.v0.700.0.aarch64-apple-darwin-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "6abfb2700f964f53f96fd86eb90b06198e87e132"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "5a283c1908ec43d40fbfb193590f10fd2f197cb01425237549c3700031ea7802"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.0+1/GAP_pkg_juliainterface.v0.700.0.aarch64-linux-gnu-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "60e48c162f6f8e2bd75cb48a542817caf60636c3"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "fab57a8b104d0e8cd11964d065f0f9baf4d5a3cc6dbb3418215829ace205b6c9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.0+1/GAP_pkg_juliainterface.v0.700.0.aarch64-linux-gnu-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "dc5cbbb4680f84bcaf746b9c9de4ba6de48d429c"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "3653b20a85344d527dd79763ed0279633b67278edef1694aa26b484c5a4d21b2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.0+1/GAP_pkg_juliainterface.v0.700.0.aarch64-linux-gnu-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "56c89f510928d0e4043a6e38d1baf7431ab796b7"
julia_version = "1.6.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "c873f3945929cb3d652e070729d2eb97f2d4fa5159e6da28d6b6266180945318"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.0+1/GAP_pkg_juliainterface.v0.700.0.aarch64-linux-musl-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "d0a2da6074bfdc016957c706a838832a7738408b"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "66f21a899fbe3a80dfe03926879452056b90715908cde4414ac6d7d119f24710"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.0+1/GAP_pkg_juliainterface.v0.700.0.aarch64-linux-musl-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "fb8faa629a54affe176092bf5d44dbdb0b5bfd4d"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "4a901be98836abe5ec04ac042f1cd11b77c681fe01ca08a685439cddbbf56d5b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.0+1/GAP_pkg_juliainterface.v0.700.0.aarch64-linux-musl-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "15ad1d940e301d11bad3666b213b34c0eefb914a"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "85946fc12c83a867ecc6a38f2e752e50d5e60172eb57572d02c01a836d0294d1"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.0+1/GAP_pkg_juliainterface.v0.700.0.powerpc64le-linux-gnu-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "30e4ba02fffe7863a209871492f123115c4a9fd7"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "e9bd04ef0fe771c742e3f96a8f0a3113ed508a35b22471aabb48a9a3bbbf92ed"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.0+1/GAP_pkg_juliainterface.v0.700.0.powerpc64le-linux-gnu-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "5764940846dfb2879f352df5f43dc558c5ad0cca"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "bee3941655b27169a57e3e5ea516a3c84d0e7b2ca0ffb54b6432d28a1c75d4db"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.0+1/GAP_pkg_juliainterface.v0.700.0.powerpc64le-linux-gnu-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "475567e024d23d3e42120e812007c9962374fab5"
julia_version = "1.6.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "c639c7d4e80670f12b589202d2a6898968e3ac3f719c8a64507acbffcc0edb15"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.0+1/GAP_pkg_juliainterface.v0.700.0.x86_64-apple-darwin-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "4b77fff6c316042cfaa1cbeca9d6e22c174162d6"
julia_version = "1.7.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "90ee15268ebf84459bfa790b1a1c62d85331c0969dee99e2fd9decf9bf56b35b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.0+1/GAP_pkg_juliainterface.v0.700.0.x86_64-apple-darwin-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "22116ac063a57ce2951202a53a16fe7606cbd091"
julia_version = "1.8.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "08bc836786d440659edeab0298b274a7c0bc47c206924a27d065e7e657c0be88"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.0+1/GAP_pkg_juliainterface.v0.700.0.x86_64-apple-darwin-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "b1ac52e6dd2017f8e674779f6386619215ce4610"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "ded2a7ae406faf429417468b8fbacc1a6d7e91620b2f75f6fce200f4e0b683f3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.0+1/GAP_pkg_juliainterface.v0.700.0.x86_64-linux-gnu-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "5fc6067641d973372e554f6a1740dc7ece415fac"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "24dff2f436e43dfdd9e44507dec2bc0e2449c7462fff1a5e386d9b09868f1d96"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.0+1/GAP_pkg_juliainterface.v0.700.0.x86_64-linux-gnu-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "062a1f15550a9bbe840186ce1f7fe522bbfd2fe9"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "2114b5724a9f2ca5fae72082821bcfdece10494d0045e2e60c98b9f089134ed6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.0+1/GAP_pkg_juliainterface.v0.700.0.x86_64-linux-gnu-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "7b9f9be030222ee1faf1833f3111932bafa3ea4e"
julia_version = "1.6.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "27fa9f9ac1c084ac945a2ca6a3a9b39b16079c2f906de5bf9f87739e762030e4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.0+1/GAP_pkg_juliainterface.v0.700.0.x86_64-linux-musl-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "3974196621d060dec162b1c4e66ba147da499322"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "b747e5a0803019b78649ab2b6a8d0eab039b8ae5ee422893ef9d267f5579f41c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.0+1/GAP_pkg_juliainterface.v0.700.0.x86_64-linux-musl-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "512c8103cacf084c657e0818d686119f8f4a9f33"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "671bd43a34c6f297cc7127b41b9dc1fcc48359bc4f7e7cb67b4957d1ffb5d61f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.0+1/GAP_pkg_juliainterface.v0.700.0.x86_64-linux-musl-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "1286fe0ebbc71dd98be67a03066c15a1a61e9d58"
julia_version = "1.6.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "98eb0f2912eb58a3e1c7c617eb4a1f8c24e1f418b6e04b7ea6b61599f6c31102"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.0+1/GAP_pkg_juliainterface.v0.700.0.x86_64-unknown-freebsd-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "afaece1fe444a3a7569c406bf6af727cce95163e"
julia_version = "1.7.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "04469aed82108d0baa0ffc9f523fc55020126f7b0c0b12f0543dd0cadb79f291"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.0+1/GAP_pkg_juliainterface.v0.700.0.x86_64-unknown-freebsd-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "ffd881cf29ba27c8189888363580c462d5392518"
julia_version = "1.8.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "ab21a9ab216f29afdd770f339146f8d42feaa7067f57d0e24290f48c61442494"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.700.0+1/GAP_pkg_juliainterface.v0.700.0.x86_64-unknown-freebsd-julia_version+1.8.0.tar.gz"
