[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "8c9cec353c3f863152fabf41d2ef8fb49b67b8c6"
julia_version = "1.7.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "dd901d1b143e4a3df889e7628e81b8d384075bf08a55f121a4cbb842fa750683"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+0/GAP_pkg_juliainterface.v0.800.200.aarch64-apple-darwin-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "85fa155a0f1576a9afc8933c394079e7c360de43"
julia_version = "1.8.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "1fc7d26b6a8693db79949605e3136e88f7ee59c652f89da06f1e7b17f094cc16"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+0/GAP_pkg_juliainterface.v0.800.200.aarch64-apple-darwin-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "9c7a0ad271d292dffc40e04bf871a960f9a65d1a"
julia_version = "1.9.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "2ceb765b080f47bea6071f55f86cf15dcd055f505b06fe10d4a89920bfda7e63"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+0/GAP_pkg_juliainterface.v0.800.200.aarch64-apple-darwin-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "3981dd220a8da0ba7c78567d6c4bd83e32ca5696"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "e5ef0ba63fd136270bd2f7ad7bca7adf9f0995067d4d8c9a7112638c54184c20"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+0/GAP_pkg_juliainterface.v0.800.200.aarch64-linux-gnu-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "2cce503189b30bb1da525ad5677fd7a0c4dde55c"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "e03bcc4801a57a6bfabf5eb3307f70fa6f17fe1e7ce20a8a7f8f5ccb5588b63b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+0/GAP_pkg_juliainterface.v0.800.200.aarch64-linux-gnu-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "0f9a6b43f09fe2e0dfd3417ec77c715b8c81e40b"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "a85f52bae544cd44e8594aaab24e6ef127b507928ff29384be580ae9fb170d73"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+0/GAP_pkg_juliainterface.v0.800.200.aarch64-linux-gnu-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "28d6e1b905e19dd8b4570f5e1307460cdcca222b"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "bdfd8d27c8a13b619656f822a4e1728e8c7c3da0b23dfe6550b731149c66c7ed"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+0/GAP_pkg_juliainterface.v0.800.200.aarch64-linux-gnu-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "a5f05828c4f572cb498b67876fc55f7020a76afa"
julia_version = "1.6.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "3099842db340a815a08851df9f36a1cea3add719f662db61e343282ccfd8c1fe"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+0/GAP_pkg_juliainterface.v0.800.200.aarch64-linux-musl-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "537530ffe3d6171bac092a6fd97a3a5ec514151c"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "3cae26077f92a53b8618703b18ae683fadcf9eca464332ab8f2443808a23bfd6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+0/GAP_pkg_juliainterface.v0.800.200.aarch64-linux-musl-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "dacbf6ab3ceda01ce6d6bbbad7a669c8a8eab6ac"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "8088b6164fbe9d1f13268f0001e2419427f2a676191b7ceb0905b498f9a914db"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+0/GAP_pkg_juliainterface.v0.800.200.aarch64-linux-musl-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "3d2929cdb2f24408d66f2505102ffe0aca25b7b6"
julia_version = "1.9.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "1e214fce0a73972fe99febb57deaa99beb12dfde9337548fae3fab7751e30163"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+0/GAP_pkg_juliainterface.v0.800.200.aarch64-linux-musl-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "ae45637f501cd6d9a5f72e6fb987b1cfe0335086"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "d8a1057d6b7c5223a0f5161ffb007d739d6337d5c0cf8e63f209cbc644931044"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+0/GAP_pkg_juliainterface.v0.800.200.powerpc64le-linux-gnu-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "11b72670da7bbfc7c5114c20d3ff3f411b57ad4c"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "6a7e5747626a086bb74895580979b129401de5bc8c31afc5640feb69e9b728c1"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+0/GAP_pkg_juliainterface.v0.800.200.powerpc64le-linux-gnu-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "b67262074daf283435700ab47dd281c7167ef5fd"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "ad0f3bb73b860f1ab7dc6aded78e72bc7491fe34d226508d154e6c55b288a578"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+0/GAP_pkg_juliainterface.v0.800.200.powerpc64le-linux-gnu-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "305bb3ee3fd12a369335d338ff8083ead645407d"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "aa00d1d753d961f1c1823706850933ae3c1d57fa8229670257b41f95f2c25a04"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+0/GAP_pkg_juliainterface.v0.800.200.powerpc64le-linux-gnu-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "5a5378049b08eb89fdbd234dfaf9669e40cb7b6b"
julia_version = "1.6.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "bd086a2bd61c2ad8c4dfb9c25e7c417b580be8724f274f3952217f0543155a95"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+0/GAP_pkg_juliainterface.v0.800.200.x86_64-apple-darwin-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "c37ec468474569cb3d1e9c1832335fc0ae8bccda"
julia_version = "1.7.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "41f7dcc97052b7c41f38b8b7cb3934994ec99fae509f5804ae2e69b2186c55bc"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+0/GAP_pkg_juliainterface.v0.800.200.x86_64-apple-darwin-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "6dc1b17fbb4089481233870c87c46b8790fe8e77"
julia_version = "1.8.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "e39c892acc4e9a75a41f652868be20ec14c24fd069f0d86f3321f688fd7c57d0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+0/GAP_pkg_juliainterface.v0.800.200.x86_64-apple-darwin-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "6efd6e85e59e51e828e49c47e6b58fc228f4dcd3"
julia_version = "1.9.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "e75c39b42cc084df6f419b218907ab400e9a56e3b70e7b266831811c7db9cd72"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+0/GAP_pkg_juliainterface.v0.800.200.x86_64-apple-darwin-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "388417a1ba9669fc99822c8e0ce771e3d49a1dde"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "ba0eb69306ae7f30b4f775b573e417af9dcec1cc8be5569301541d4ed462ccf6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+0/GAP_pkg_juliainterface.v0.800.200.x86_64-linux-gnu-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "ab15540f5299164d396c811a91e67d4ca22a2573"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "0ca03716fce1a640344fcb86bbbf259b952e16f72781491251e2359a719f11bf"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+0/GAP_pkg_juliainterface.v0.800.200.x86_64-linux-gnu-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "33c9e3d5a1b7218740ca6662cd4582e8513ab7da"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "e5182192b7eb4d96346ed4daa2fcd47c7f9fc152393f29f1e5a8292067c0ba9e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+0/GAP_pkg_juliainterface.v0.800.200.x86_64-linux-gnu-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "1fc57ecc7f12b81d74159c88c91959308365b82c"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "e34c062ec50b1413f148b0ce826fd5dfe13a33e97c5482125b282ed2b6c2a2a9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+0/GAP_pkg_juliainterface.v0.800.200.x86_64-linux-gnu-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "1a8b82e5c23350fd5ae2b84b40f55be32ef5ddae"
julia_version = "1.6.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "4935b5fbc56fbcbca7fbfd2af84acf9b189b23d2acdeafae4a17c6a47d27f5cb"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+0/GAP_pkg_juliainterface.v0.800.200.x86_64-linux-musl-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "e786542dd66b46f6ad37baa5ff4a1b535b98c269"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "a451a9e39b9f3231ae1577c976a55bdf5e7caa25c8b925155edc88ab8207f723"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+0/GAP_pkg_juliainterface.v0.800.200.x86_64-linux-musl-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "1462b2873b99784725903b90306f136d93894fdd"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "cd7d317609d7120aba9e123736cb282cf9be429d1a27635f2a7790fe2176692b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+0/GAP_pkg_juliainterface.v0.800.200.x86_64-linux-musl-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "b7d6988f60f1992f0df8a289607646ef7ad5ecae"
julia_version = "1.9.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "462305e8e621ca525bff5a1f1e52ea5adddc1629a9f639903d4d20e638c24053"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+0/GAP_pkg_juliainterface.v0.800.200.x86_64-linux-musl-julia_version+1.9.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "b52f89ef0f139db8ae8dd0d0b1c4c4ca6d7d148d"
julia_version = "1.6.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "62aeb1fe534d5db1be244d2d16f51ebbcc6c06fd393ca63332c2712949e56014"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+0/GAP_pkg_juliainterface.v0.800.200.x86_64-unknown-freebsd-julia_version+1.6.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "06e464fbb30d5a1c3d5c0b3447f6e3e0ae9b6244"
julia_version = "1.7.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "7e38fb130826108a5b6be4fb89503789beb57443c02a78875f42ef32fc8a4d15"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+0/GAP_pkg_juliainterface.v0.800.200.x86_64-unknown-freebsd-julia_version+1.7.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "6523c4a8d6c8d70c03c05d0e0bec62681820cea9"
julia_version = "1.8.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "10f028b355505a83dfabcd0ea1c0b919a8d3d624160e1c61e966c526186a06a1"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+0/GAP_pkg_juliainterface.v0.800.200.x86_64-unknown-freebsd-julia_version+1.8.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "3f3c0b69f7decf459daf44e3faf28835b35ddc25"
julia_version = "1.9.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "b17f1e123d833c299143bf920536b9e9cff0e2c6155d4584482a9807937fdbd9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.800.200+0/GAP_pkg_juliainterface.v0.800.200.x86_64-unknown-freebsd-julia_version+1.9.0.tar.gz"
